package main

import (
	"fmt"
	blsu "github.com/protolambda/bls12-381-util"
	"os"
	"strings"
	"time"

	"github.com/ethereum/hive/hivesim"
	"github.com/ethereum/hive/simulators/eth2/testnet/setup"
	"github.com/protolambda/zrnt/eth2/beacon/common"
	"github.com/protolambda/zrnt/eth2/configs"
)

var depositAddress common.Eth1Address
var mnemonic = "couple kiwi radio river setup fortune hunt grief buddy forward perfect empty slim wear bounce drift execute nation tobacco dutch chapter festival ice fog"

func init() {
	_ = depositAddress.UnmarshalText([]byte("0x4242424242424242424242424242424242424242"))
}

// PreparedTestnet has all the options for starting nodes, ready to build the network.
type PreparedTestnet struct {
	// Consensus chain configuration
	spec *common.Spec

	// Execution chain configuration and genesis info
	eth1Genesis *setup.Eth1Genesis
	// Consensus genesis state
	eth2Genesis common.BeaconState
	// Secret keys of validators, to fabricate extra signed test messages with during testnet/
	// E.g. to test a slashable offence that would not otherwise happen.
	keys []blsu.SecretKey

	// Configuration to apply to every node of the given type
	executionOpts []hivesim.StartOption
	validatorOpts []hivesim.StartOption
	beaconOpts    []hivesim.StartOption

	// A tranche is a group of validator keys to run on 1 node
	keyTranches []hivesim.StartOption
}

// Build all artifacts require to start a testnet.
func prepareTestnet(t *hivesim.T, config *Config) *PreparedTestnet {
	eth1GenesisTime := uint64(time.Now().Unix())
	// Generate genesis for execution clients
	eth1Genesis := setup.BuildEth1Genesis(config.TotalTerminalDifficulty, eth1GenesisTime)
	eth1ConfigOpt := eth1Genesis.ToParams(depositAddress)
	eth1Bundle, err := setup.Eth1Bundle(eth1Genesis.Genesis)
	if err != nil {
		t.Fatal(err)
	}
	execNodeOpts := hivesim.Params{
		"HIVE_CATALYST_ENABLED": "1",
		"HIVE_LOGLEVEL":         os.Getenv("HIVE_LOGLEVEL"),
		"HIVE_NODETYPE":         "full",
	}
	executionOpts := []hivesim.StartOption{eth1ConfigOpt, eth1Bundle, execNodeOpts}

	// Generate beacon spec
	//
	// TODO: specify build-target based on preset, to run clients in mainnet or minimal mode.
	// copy the default mainnet config, and make some minimal modifications for testnet usage
	delay := 30
	if config.MergeForkEpoch != 0 {
		delay = 60 * 2
	}
	specCpy := *configs.Mainnet
	spec := &specCpy
	spec.Config.DEPOSIT_CONTRACT_ADDRESS = depositAddress
	spec.Config.DEPOSIT_CHAIN_ID = eth1Genesis.Genesis.Config.ChainID.Uint64()
	spec.Config.DEPOSIT_NETWORK_ID = eth1Genesis.NetworkID
	spec.Config.MIN_GENESIS_TIME = common.Timestamp(eth1Genesis.Genesis.Timestamp)
	spec.Config.GENESIS_DELAY = common.Timestamp(delay)
	spec.Config.ETH1_FOLLOW_DISTANCE = 1
	spec.AltairPreset.SYNC_COMMITTEE_SIZE = 4

	spec.Config.ALTAIR_FORK_EPOCH = common.Epoch(config.AltairForkEpoch)
	spec.Config.MERGE_FORK_EPOCH = common.Epoch(config.MergeForkEpoch)
	spec.Config.MIN_GENESIS_ACTIVE_VALIDATOR_COUNT = config.ValidatorCount
	spec.Config.SECONDS_PER_SLOT = common.Timestamp(config.SlotTime)
	spec.Config.TERMINAL_TOTAL_DIFFICULTY = common.MustU256FromBig(config.TotalTerminalDifficulty)

	// Generate keys for validators
	t.Logf("generating %d validator keys...", config.ValidatorCount)
	keySrc := &setup.MnemonicsKeySource{
		From:       0,
		To:         config.ValidatorCount,
		Validator:  mnemonic,
		Withdrawal: mnemonic,
	}
	keys, err := keySrc.Keys()
	if err != nil {
		t.Fatal(err)
	}
	secrets, err := setup.SecretKeys(keys)
	if err != nil {
		t.Fatal(err)
	}

	keyOpts := setup.KeyTranches(keys, uint64(len(config.Nodes)))

	consensusConfigOpts, err := setup.ConsensusConfigsBundle(spec, eth1Genesis.Genesis, config.ValidatorCount)
	if err != nil {
		t.Fatal(err)
	}
	// prepare genesis beacon state, with all of the validators in it.
	state, err := setup.BuildBeaconState(eth1Genesis, spec, keys)
	if err != nil {
		t.Fatal(err)
	}

	// Write info so that the genesis state can be generated by the client
	stateOpt, err := setup.StateBundle(state, common.Timestamp(eth1GenesisTime))

	// Define additional start options for beacon chain
	commonOpts := hivesim.Params{
		"HIVE_ETH2_BN_API_PORT":                     fmt.Sprintf("%d", PortBeaconAPI),
		"HIVE_ETH2_BN_GRPC_PORT":                    fmt.Sprintf("%d", PortBeaconGRPC),
		"HIVE_ETH2_METRICS_PORT":                    fmt.Sprintf("%d", PortMetrics),
		"HIVE_ETH2_CONFIG_DEPOSIT_CONTRACT_ADDRESS": depositAddress.String(),
	}
	beaconOpts := []hivesim.StartOption{
		commonOpts,
		hivesim.Params{
			"HIVE_CHECK_LIVE_PORT":        fmt.Sprintf("%d", PortBeaconAPI),
			"HIVE_ETH2_MERGE_ENABLED":     "1",
			"HIVE_ETH2_ETH1_GENESIS_TIME": fmt.Sprintf("%d", eth1Genesis.Genesis.Timestamp),
			"HIVE_ETH2_GENESIS_FORK":      config.activeFork(),
		},
		stateOpt,
	}
	beaconOpts = append(beaconOpts, consensusConfigOpts...)

	validatorOpts := []hivesim.StartOption{
		commonOpts,
		hivesim.Params{
			"HIVE_CHECK_LIVE_PORT": "0",
		},
	}
	validatorOpts = append(validatorOpts, consensusConfigOpts...)

	return &PreparedTestnet{
		spec:          spec,
		eth1Genesis:   eth1Genesis,
		eth2Genesis:   state,
		keys:          secrets,
		executionOpts: executionOpts,
		beaconOpts:    beaconOpts,
		validatorOpts: validatorOpts,
		keyTranches:   keyOpts,
	}
}

func (p *PreparedTestnet) createTestnet(t *hivesim.T) *Testnet {
	genesisTime, _ := p.eth2Genesis.GenesisTime()
	genesisValidatorsRoot, _ := p.eth2Genesis.GenesisValidatorsRoot()
	return &Testnet{
		t:                     t,
		genesisTime:           genesisTime,
		genesisValidatorsRoot: genesisValidatorsRoot,
		spec:                  p.spec,
		eth1Genesis:           p.eth1Genesis,
	}
}

func (p *PreparedTestnet) startEth1Node(testnet *Testnet, eth1Def *hivesim.ClientDefinition, simulated bool) {
	testnet.t.Logf("starting eth1 node: %s (%s)", eth1Def.Name, eth1Def.Version)

	opts := p.executionOpts
	if len(testnet.eth1) == 0 {
		if !simulated {
			// we only make the first eth1 node a miner
			opts = append(opts, hivesim.Params{"HIVE_MINER": "0x1212121212121212121212121212121212121212"})
		}
	} else {
		bootnode, err := testnet.eth1[0].EnodeURL()
		if err != nil {
			testnet.t.Fatalf("failed to get eth1 bootnode URL: %v", err)
		}

		// Make the client connect to the first eth1 node, as a bootnode for the eth1 net
		opts = append(opts, hivesim.Params{"HIVE_BOOTNODE": bootnode})
	}

	en := &Eth1Node{testnet.t.StartClient(eth1Def.Name, opts...)}
	testnet.eth1 = append(testnet.eth1, en)
}

func (p *PreparedTestnet) startBeaconNode(testnet *Testnet, beaconDef *hivesim.ClientDefinition, eth1Endpoints []int) {
	testnet.t.Logf("starting beacon node: %s (%s)", beaconDef.Name, beaconDef.Version)

	opts := p.beaconOpts
	// Hook up beacon node to (maybe multiple) eth1 nodes
	for _, index := range eth1Endpoints {
		if index < 0 || index >= len(testnet.eth1) {
			testnet.t.Fatalf("only have %d eth1 nodes, cannot find index %d for BN", len(testnet.eth1), index)
		}
	}

	var addrs []string
	for _, index := range eth1Endpoints {
		eth1Node := testnet.eth1[index]
		userRPC, err := eth1Node.UserRPCAddress()
		if err != nil {
			testnet.t.Fatalf("eth1 node used for beacon without available RPC: %v", err)
		}
		addrs = append(addrs, userRPC)
	}
	opts = append(opts, hivesim.Params{"HIVE_ETH2_ETH1_RPC_ADDRS": strings.Join(addrs, ",")})

	if len(testnet.beacons) > 0 {
		bootnodeENR, err := testnet.beacons[0].ENR()
		if err != nil {
			testnet.t.Fatalf("failed to get ENR as bootnode for beacon node: %v", err)
		}
		opts = append(opts, hivesim.Params{"HIVE_ETH2_BOOTNODE_ENRS": bootnodeENR})
	}

	// TODO
	//if p.configName != "mainnet" && hasBuildTarget(beaconDef, p.configName) {
	//	opts = append(opts, hivesim.WithBuildTarget(p.configName))
	//}
	bn := NewBeaconNode(testnet.t.StartClient(beaconDef.Name, opts...))
	testnet.beacons = append(testnet.beacons, bn)
}

func (p *PreparedTestnet) startValidatorClient(testnet *Testnet, validatorDef *hivesim.ClientDefinition, bnIndex int, keyIndex int) {
	testnet.t.Logf("starting validator client: %s (%s)", validatorDef.Name, validatorDef.Version)

	if bnIndex >= len(testnet.beacons) {
		testnet.t.Fatalf("only have %d beacon nodes, cannot find index %d for VC", len(testnet.beacons), bnIndex)
	}
	bn := testnet.beacons[bnIndex]
	// Hook up validator to beacon node
	bnAPIOpt := hivesim.Params{
		"HIVE_ETH2_BN_API_IP": bn.IP.String(),
	}
	if keyIndex >= len(p.keyTranches) {
		testnet.t.Fatalf("only have %d key tranches, cannot find index %d for VC", len(p.keyTranches), keyIndex)
	}
	keysOpt := p.keyTranches[keyIndex]
	opts := p.validatorOpts
	opts = append(opts, keysOpt)
	opts = append(opts, bnAPIOpt)
	// TODO
	//if p.configName != "mainnet" && hasBuildTarget(validatorDef, p.configName) {
	//	opts = append(opts, hivesim.WithBuildTarget(p.configName))
	//}
	vc := &ValidatorClient{testnet.t.StartClient(validatorDef.Name, opts...)}
	testnet.validators = append(testnet.validators, vc)
}
