package main

var envForks = map[string]map[string]int{
	"Merge": {
		"HIVE_FORK_HOMESTEAD":            0,
		"HIVE_FORK_TANGERINE":            0,
		"HIVE_FORK_SPURIOUS":             0,
		"HIVE_FORK_BYZANTIUM":            0,
		"HIVE_FORK_CONSTANTINOPLE":       0,
		"HIVE_FORK_PETERSBURG":           0,
		"HIVE_FORK_ISTANBUL":             0,
		"HIVE_FORK_BERLIN":               0,
		"HIVE_FORK_LONDON":               0,
		"HIVE_FORK_MERGE":                0,
		"HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
	},
	"Shanghai": {
		"HIVE_FORK_HOMESTEAD":            0,
		"HIVE_FORK_TANGERINE":            0,
		"HIVE_FORK_SPURIOUS":             0,
		"HIVE_FORK_BYZANTIUM":            0,
		"HIVE_FORK_CONSTANTINOPLE":       0,
		"HIVE_FORK_PETERSBURG":           0,
		"HIVE_FORK_ISTANBUL":             0,
		"HIVE_FORK_BERLIN":               0,
		"HIVE_FORK_LONDON":               0,
		"HIVE_FORK_MERGE":                0,
		"HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
		"HIVE_SHANGHAI_TIMESTAMP":        0,
	},
	"MergeToShanghaiAtTime15k": {
		"HIVE_FORK_HOMESTEAD":            0,
		"HIVE_FORK_TANGERINE":            0,
		"HIVE_FORK_SPURIOUS":             0,
		"HIVE_FORK_BYZANTIUM":            0,
		"HIVE_FORK_CONSTANTINOPLE":       0,
		"HIVE_FORK_PETERSBURG":           0,
		"HIVE_FORK_ISTANBUL":             0,
		"HIVE_FORK_BERLIN":               0,
		"HIVE_FORK_LONDON":               0,
		"HIVE_FORK_MERGE":                0,
		"HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
		"HIVE_SHANGHAI_TIMESTAMP":        15000,
	},
}
