// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package main

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/math"
)

var _ = (*withdrawals)(nil)

// MarshalJSON marshals as JSON.
func (w withdrawals) MarshalJSON() ([]byte, error) {
	type withdrawals struct {
		Index          *math.HexOrDecimal256 `json:"index"`
		ValidatorIndex *math.HexOrDecimal256 `json:"validatorIndex"`
		Address        *common.Address       `json:"address"`
		Amount         *math.HexOrDecimal256 `json:"amount"`
	}
	var enc withdrawals
	enc.Index = w.Index
	enc.ValidatorIndex = w.ValidatorIndex
	enc.Address = w.Address
	enc.Amount = w.Amount
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (w *withdrawals) UnmarshalJSON(input []byte) error {
	type withdrawals struct {
		Index          *math.HexOrDecimal256 `json:"index"`
		ValidatorIndex *math.HexOrDecimal256 `json:"validatorIndex"`
		Address        *common.Address       `json:"address"`
		Amount         *math.HexOrDecimal256 `json:"amount"`
	}
	var dec withdrawals
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Index != nil {
		w.Index = dec.Index
	}
	if dec.ValidatorIndex != nil {
		w.ValidatorIndex = dec.ValidatorIndex
	}
	if dec.Address != nil {
		w.Address = dec.Address
	}
	if dec.Amount != nil {
		w.Amount = dec.Amount
	}
	return nil
}
