// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package main

import (
	"encoding/json"
	"errors"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*payloadAttributesMarshalingBytes)(nil)

// MarshalJSON marshals as JSON.
func (p PayloadAttributesBytes) MarshalJSON() ([]byte, error) {
	type PayloadAttributesBytes struct {
		Timestamp             hexutil.Uint64 `json:"timestamp"              gencodec:"required"`
		PrevRandao            hexutil.Bytes  `json:"prevRandao"             gencodec:"required"`
		SuggestedFeeRecipient hexutil.Bytes  `json:"suggestedFeeRecipient"  gencodec:"required"`
	}
	var enc PayloadAttributesBytes
	enc.Timestamp = hexutil.Uint64(p.Timestamp)
	enc.PrevRandao = p.PrevRandao
	enc.SuggestedFeeRecipient = p.SuggestedFeeRecipient
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (p *PayloadAttributesBytes) UnmarshalJSON(input []byte) error {
	type PayloadAttributesBytes struct {
		Timestamp             *hexutil.Uint64 `json:"timestamp"              gencodec:"required"`
		PrevRandao            *hexutil.Bytes  `json:"prevRandao"             gencodec:"required"`
		SuggestedFeeRecipient *hexutil.Bytes  `json:"suggestedFeeRecipient"  gencodec:"required"`
	}
	var dec PayloadAttributesBytes
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Timestamp == nil {
		return errors.New("missing required field 'timestamp' for PayloadAttributesBytes")
	}
	p.Timestamp = uint64(*dec.Timestamp)
	if dec.PrevRandao == nil {
		return errors.New("missing required field 'prevRandao' for PayloadAttributesBytes")
	}
	p.PrevRandao = *dec.PrevRandao
	if dec.SuggestedFeeRecipient == nil {
		return errors.New("missing required field 'suggestedFeeRecipient' for PayloadAttributesBytes")
	}
	p.SuggestedFeeRecipient = *dec.SuggestedFeeRecipient
	return nil
}
