// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package main

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*executableDataMarshalingByteType)(nil)

// MarshalJSON marshals as JSON.
func (e ExecutableDataByteType) MarshalJSON() ([]byte, error) {
	type ExecutableDataByteType struct {
		ParentHash    hexutil.Bytes   `json:"parentHash"    gencodec:"required"`
		FeeRecipient  hexutil.Bytes   `json:"feeRecipient"  gencodec:"required"`
		StateRoot     hexutil.Bytes   `json:"stateRoot"     gencodec:"required"`
		ReceiptsRoot  hexutil.Bytes   `json:"receiptsRoot"  gencodec:"required"`
		LogsBloom     hexutil.Bytes   `json:"logsBloom"     gencodec:"required"`
		PrevRandao    hexutil.Bytes   `json:"prevRandao"    gencodec:"required"`
		Number        hexutil.Uint64  `json:"blockNumber"   gencodec:"required"`
		GasLimit      hexutil.Uint64  `json:"gasLimit"      gencodec:"required"`
		GasUsed       hexutil.Uint64  `json:"gasUsed"       gencodec:"required"`
		Timestamp     hexutil.Uint64  `json:"timestamp"     gencodec:"required"`
		ExtraData     hexutil.Bytes   `json:"extraData"     gencodec:"required"`
		BaseFeePerGas *hexutil.Big    `json:"baseFeePerGas" gencodec:"required"`
		BlockHash     hexutil.Bytes   `json:"blockHash"     gencodec:"required"`
		Transactions  []hexutil.Bytes `json:"transactions"  gencodec:"required"`
	}
	var enc ExecutableDataByteType
	enc.ParentHash = e.ParentHash
	enc.FeeRecipient = e.FeeRecipient
	enc.StateRoot = e.StateRoot
	enc.ReceiptsRoot = e.ReceiptsRoot
	enc.LogsBloom = e.LogsBloom
	enc.PrevRandao = e.PrevRandao
	enc.Number = hexutil.Uint64(e.Number)
	enc.GasLimit = hexutil.Uint64(e.GasLimit)
	enc.GasUsed = hexutil.Uint64(e.GasUsed)
	enc.Timestamp = hexutil.Uint64(e.Timestamp)
	enc.ExtraData = e.ExtraData
	enc.BaseFeePerGas = (*hexutil.Big)(e.BaseFeePerGas)
	enc.BlockHash = e.BlockHash
	if e.Transactions != nil {
		enc.Transactions = make([]hexutil.Bytes, len(e.Transactions))
		for k, v := range e.Transactions {
			enc.Transactions[k] = v
		}
	}
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (e *ExecutableDataByteType) UnmarshalJSON(input []byte) error {
	type ExecutableDataByteType struct {
		ParentHash    *hexutil.Bytes  `json:"parentHash"    gencodec:"required"`
		FeeRecipient  *hexutil.Bytes  `json:"feeRecipient"  gencodec:"required"`
		StateRoot     *hexutil.Bytes  `json:"stateRoot"     gencodec:"required"`
		ReceiptsRoot  *hexutil.Bytes  `json:"receiptsRoot"  gencodec:"required"`
		LogsBloom     *hexutil.Bytes  `json:"logsBloom"     gencodec:"required"`
		PrevRandao    *hexutil.Bytes  `json:"prevRandao"    gencodec:"required"`
		Number        *hexutil.Uint64 `json:"blockNumber"   gencodec:"required"`
		GasLimit      *hexutil.Uint64 `json:"gasLimit"      gencodec:"required"`
		GasUsed       *hexutil.Uint64 `json:"gasUsed"       gencodec:"required"`
		Timestamp     *hexutil.Uint64 `json:"timestamp"     gencodec:"required"`
		ExtraData     *hexutil.Bytes  `json:"extraData"     gencodec:"required"`
		BaseFeePerGas *hexutil.Big    `json:"baseFeePerGas" gencodec:"required"`
		BlockHash     *hexutil.Bytes  `json:"blockHash"     gencodec:"required"`
		Transactions  []hexutil.Bytes `json:"transactions"  gencodec:"required"`
	}
	var dec ExecutableDataByteType
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ParentHash == nil {
		return errors.New("missing required field 'parentHash' for ExecutableDataByteType")
	}
	e.ParentHash = *dec.ParentHash
	if dec.FeeRecipient == nil {
		return errors.New("missing required field 'feeRecipient' for ExecutableDataByteType")
	}
	e.FeeRecipient = *dec.FeeRecipient
	if dec.StateRoot == nil {
		return errors.New("missing required field 'stateRoot' for ExecutableDataByteType")
	}
	e.StateRoot = *dec.StateRoot
	if dec.ReceiptsRoot == nil {
		return errors.New("missing required field 'receiptsRoot' for ExecutableDataByteType")
	}
	e.ReceiptsRoot = *dec.ReceiptsRoot
	if dec.LogsBloom == nil {
		return errors.New("missing required field 'logsBloom' for ExecutableDataByteType")
	}
	e.LogsBloom = *dec.LogsBloom
	if dec.PrevRandao == nil {
		return errors.New("missing required field 'prevRandao' for ExecutableDataByteType")
	}
	e.PrevRandao = *dec.PrevRandao
	if dec.Number == nil {
		return errors.New("missing required field 'blockNumber' for ExecutableDataByteType")
	}
	e.Number = uint64(*dec.Number)
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for ExecutableDataByteType")
	}
	e.GasLimit = uint64(*dec.GasLimit)
	if dec.GasUsed == nil {
		return errors.New("missing required field 'gasUsed' for ExecutableDataByteType")
	}
	e.GasUsed = uint64(*dec.GasUsed)
	if dec.Timestamp == nil {
		return errors.New("missing required field 'timestamp' for ExecutableDataByteType")
	}
	e.Timestamp = uint64(*dec.Timestamp)
	if dec.ExtraData == nil {
		return errors.New("missing required field 'extraData' for ExecutableDataByteType")
	}
	e.ExtraData = *dec.ExtraData
	if dec.BaseFeePerGas == nil {
		return errors.New("missing required field 'baseFeePerGas' for ExecutableDataByteType")
	}
	e.BaseFeePerGas = (*big.Int)(dec.BaseFeePerGas)
	if dec.BlockHash == nil {
		return errors.New("missing required field 'blockHash' for ExecutableDataByteType")
	}
	e.BlockHash = *dec.BlockHash
	if dec.Transactions == nil {
		return errors.New("missing required field 'transactions' for ExecutableDataByteType")
	}
	e.Transactions = make([][]byte, len(dec.Transactions))
	for k, v := range dec.Transactions {
		e.Transactions[k] = v
	}
	return nil
}
