// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "github.com/ethereum/hive/simulators/ethereum/engine/helper"
)

func main() {
  g := gen.NewGenerator("core_easyjson.go")
  g.SetPkg("helper", "github.com/ethereum/hive/simulators/ethereum/engine/helper")
  g.Add(pkg.EasyJSON_exporter_AuthorityParams(nil))
  g.Add(pkg.EasyJSON_exporter_Builtin(nil))
  g.Add(pkg.EasyJSON_exporter_ErigonAccount(nil))
  g.Add(pkg.EasyJSON_exporter_ErigonAura(nil))
  g.Add(pkg.EasyJSON_exporter_ErigonConfig(nil))
  g.Add(pkg.EasyJSON_exporter_ErigonGenesis(nil))
  g.Add(pkg.EasyJSON_exporter_NethermindChainSpec(nil))
  g.Add(pkg.EasyJSON_exporter_NethermindEngine(nil))
  g.Add(pkg.EasyJSON_exporter_NethermindGenesis(nil))
  g.Add(pkg.EasyJSON_exporter_NethermindParams(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
