// Code generated by "esc -pkg assets -o assets/assets.go -prefix assets/ assets/"; DO NOT EDIT.

package assets

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/app-viewer.js": {
		name:    "app-viewer.js",
		local:   "assets/app-viewer.js",
		size:    4520,
		modtime: 1603658490,
		compressed: `
H4sIAAAAAAAC/6xXX3PjthF/16fYIDdz5JmmYrdP1uk6zU1uclOlk4mdp6YPELE0YYMAA4CWXY++e2cB
SgRpy+l04gdZIvb//va34HIJNw0C77oCWmMRjAWFzpXwTwO15S3ujL13oBEFgvENWvAN18DBdYq7BkwN
d7/3aJ8WD9xCw6t7B2t4XgAALD+Efy2/x43UCJVF7tEB14AKW9QelLxH8A2Cx7ZT3CM0aPEq6AHAR28/
Hb7TLwFSrNnm+RkUGdzvGVSKO7dmum9ZeLhm4ymwTx+XXkxNfHp+hspoT+73+8n5x+XB34flJPQrqHtd
eWl0pvt2i7YAj48+HxKlP4UevIU1CFP1lFsZ0/0hZpoxb1k+lRYXb4mLRNyLi9Kh/7v3Vm57jxmTghXA
NgzOoOPW4Vfth9Dyt9RCtUiT6vWWIFWQFW/Yjhlc/u8ZXJZSa7Q3+OhhHco3HtqSdx1q8bmRSmReXOSr
04eXyaFF31sN3oYn+2IRgbcEh/7HDX26AK9G3jZK3jbRZzic9jRt5buMlUcFFCwvLbbmAT9T8TI2OVqR
M9N72EnfBFdGidTSt6FH5KHsuKXC5CUX4qQtqUdTGnfzvJq+5RoscsG3CqHX0rtwFr4lOSlTzeFJIrAG
9j07PpY1kCR8govvLv+aKgQlU8E6fC7D+eTwYA3+kdjb/5mWf3rV8NByZarSmy/yEUV2mcNZ0Fq9gEFj
dgFxQhJhPTngsO11FYiLMAhGh1JLgdrLWqI4cFNEyqCfFFaY9qsoohV+8woLVEbgf9K5uEU/DMX3T19F
NDAdJJo24s3RaOk6JX3GftPJENXGQkbyEtbw3QokfIyqpUJ965sVyLOzF6VGH1KCdaTn8kBqmYQzuCii
hX/Jf+cTtZDFZPLISP5KQ2iJUCWpVlLfgjAaC9BmR67fO9hJi9B3ocy3vfdozyslq3upb1MbzhBmeOTu
SDcgHQRRFEUqelHCzxYfpOndONkkHOdUpLKXZVhxwapMxGcm/xLFpCAhLgQK8CaE/OsvG2i4ayb0EOiz
NDp7H+J7X4z4MNu7eQti3QPrZO8y30iXl9x7O9BsPq18I5039qnsetdce+4x071SBcRP9i3xydSKFCxP
SHGfrxZpbtfooUXPz6WuTTkBHj2mQUxABGfAgPDhCiBXMfhAL1mCzyiceD0Fd0Y+WD5hf3r0gsTTICZz
TMC67oJ+Moeuk3o+ei5KwTowb8ulhlIZLtCyJNKDZODgMHdsUDzfGivQwvTnuWvZakJsc98hyqgzknvi
Im0OoHJ4QjfdMyfUX1l0n4fbDNWJCK6WCuEs/KOOJ1zYKwFbhIorhQK2TwHgsUAF8NpT6n1VoXN1rxTU
6KvmsDEHL0kHiD+L4EbzFtN6nMTCg8QdNSOi4cebnzZU/aS6ejNQ4TAzA/8eNYeL12qOb0rE8h0IdP6P
w7B8d95bxfLZraexWLMkpeM+2S8Wy2WsxxeqLtXMEalxWtKx4t4ABbk41GcUzwL7LD+A6eiAK7jr244U
wsGHJRyKF9a0VQOAySx5Ynn5wFUWaWIszDATmbf9IdR3Jb/jj9nYid6qK/oYyU5wz2+eOrwCRqVk48nQ
+nTXcc9PkFniv+bKYdKSQyIadw65rRrq8d8omTURSm/VVJYmaie1MLtSmYqT53JQ/GY9WpkH8sdcOapO
He4nv44o8dIrhPXLAI/8PcxAqEtBcvlJnqfO5i/SDE9fyWOePi0cqlq4PJLSqQT2Y/vQWpMS5N3vBTjP
fe+KePb/dZIrtD5jX7hUcSkSImFoJC2L33T0ckXP4tf4OAZET6P71TxqWlT7xTgwmj/IW2riIdLlEj43
WN2Hm8/kYqDDTo7LjN48dU8XHGp79PIapoKG67fO2+yigIsc1qHEaV2ineNrz1smLg87d/8y1kAIRCHl
caw7bnlLzEaE8esvm+uAzJ/D02yG+3xMIqrNF10dg+StI27LGPlLVxxp1vN+v0IpdX4CETPSZRvDBV3u
SL8sSzYDyUh19KYzPTu+o/X4Yo8tEoEAvgCId9lhJunVi4un7AjqQ06U4DcjXtJUaSM0hlZBzXvl4zV/
ixXvHYI2vqE8dtzFxSfGC9HJ7E/uEXzkbacw8Giy0ya4GCDEhfjhAbXfSOeRZu19ZzqaFkwvjzk8p1MQ
BiRfLf4bAAD//6qI6yuoEQAA
`,
	},

	"/app.js": {
		name:    "app.js",
		local:   "assets/app.js",
		size:    17010,
		modtime: 1604572067,
		compressed: `
H4sIAAAAAAAC/7R7X3fbuPHouz/FLJtGZCyRkuzYsWzZu82f27TZzZ4ke/bcWj4pREISbApgAVCyu/F9
vW/3Q95P8jsDgBRJUY6z3eYhloDBYGYwmL9QLLjSIKnKU60+CKFhDF7kvkfe3l6uWapgDL/tAQBEz8wf
eAZ//fTjux7lsUgYn7vByPxd6GX62czQEcxyHmsmuK+0DBwSgyh6RzXoBYVX73+ERADTMBMSchWWMCsi
IYExJCLOl5TrMJaUaPo6pfjN72h6q4mkpBOclmuSkHFO5Sd6i5woLU8rW/5vqrrwtrMEsiaSgphV5mCh
dTaKIqVJfCNWVM5SsQ5jsYz+lVOFLKhoMBycvDjqR8hhyXuP8d41WREVS5bp3vW/cirvqojfwnWuNCSC
dzSQuaR0w6KkOpe8oBplaum975o/ew4F5THJVJ4STSEhmgDjiiUUCGhiha/JvCJsfZd14Y+XuL7Ldora
9zzYN3uebnMnct3grkWb4AetJZvmmkKrXhGt5Vf16nY39d6tV6HtNlRUlzv63tTrNqhHYZA0hTHcNhmo
MEfSNFT5VGnJ+Nw/6pqBlPK5XkAPjoJdHL9iUt9BLtNeRqRifA5iZk4nlyksiFqAonOkuyaDOdWfcfJz
RiRZqoocqkJAyiXVK4LE/3ZfGzfqCWNYM56IdZiKmOD6ELFWGBk0BLEiEq2AWR2qLGXa7zytXjxUJR8h
GYyhfwoMzswiJ4tTYPv7VRoLxBlhEsYG9JJdFajHVdRO2iuSXiYUj/+XD29fimUmOB4rIrjsXwVXePI7
pgdXQYntvnmCFvWuc3ppdEgB4UB4vBCyR60+wUyKJXRyrmWuNE06kDJ+Ax28n52tQ8O5ymnlMu0C2q/m
sZEH7F3N0JGG/i4knXld1J4akLa3E/9sq27LvSzovVZNkq/Vf4dib2M8R2hCrtV/xEBhMj/QLCUxVfDL
h3cKGAfGs1zDmumFtTbInjN9uUzVZy0Mx+ohnwWfFoTfqG7hLHKZSjqnt8ZPlHApRY8KY4h8378YIeyl
uroYTaJJFPgXo8tJ73T0dDzZnzzpTtZX+98HF5c/9P5Bev/u904m4aR3tf/Fvxit1+tJ+GUbuAkb4CaT
6HKy/3/+PIkm4WQ96X2+ehZcTC4u7G6T/fHT0z9/j1M48Sc7HE6+m0STyWR99SwILoKoKd2P1hKgEEJp
pelL2i3FA/6S6HjRvNRutYkbwkL1LWgX7IrNQd4HLf6uefeKr2fTXGvBQd9ldOzZLx7EKVFq7E01h6nm
vYTOSJ5q7/yV/XAWWcDzrStpxyvHLXicsvjm29XcYnpI15Fk1HVH9AOQhh0D6hjKJFsSeWc+3yovaNyN
l4JrtEbNK9LE65jzuuA+BY++TTMhl0R/1mxJVUaqEksGXUiGTVElbDZDaQ2hB8mg7kc+oxfxvM0gm4Fv
FpxBv6lKFrjn1V2BQ9/Dv6ctZr0IYn4kehHOUiGk3SCCF0eHffxXDWJw5s/jcqpO7aIVzcHRLixupo5k
2YrkaAeKo20EqhXBwK7fVlK4AD+BffASL4BRTdgE9sfg+wS+fIFFgIALBFw4wKAdcmkglwi5LCAx1sMB
5W1Z5c84QbYM8iJfEnS2JCHTlELOmbY323yqKFUq4qoioIKkIoYzGPSHhzusDQLsg/cXr0UfcG5s/o8M
im/GHGrxht3SxB8i297f/+Kdfss2OxH9WCBqRB2vbzMaaxNyiOk1jTWk7IaW+OpkepJmwhuBh25GjaJo
zvQinxqPRPWCSpovo7noFZ+9bn15LJZLphFBfziID+Lhi8HR8GRKZkNK6MnRcRIPZ31y/PxgmCSzJB7M
pk0MU4mBEWKQNKVE0WgQHjUP4leWpqWhsZGSFibelWy+0GDcC7ppM0QzYSViAEfwSN4iLSmNHsuHzZsw
vBhBG7bvHSK4/P//7/9ChbervaonMSR9oJl4V4+XMA5s6jGOoS8VMB6bW9Sqcl6rfpXr7Yk9iKHc50FE
9uAehwj19XsMzyokhCplMfX7XTgOdhliF749Gg/OW4GXQI7MffCuGn7juxJtqDSRWv3K9MIvb4IXPBib
VOoUvvH4p2imuNDuTCsc/TEBryZyTjX69s/TlPCbqr2NIvhIta0UGDnNmFT6a7FzyX8d0y+KQkb0wiRl
yNp2PE1CBOBkSZ30B8HjjmaSDw9eHH/tdBw7U6EXlh3CEzC302nvikrFBH80g7iBvd4NCoNHZAV793t7
eLRkBUwZ86M1uiDNUqbv0BApLSQFvWB8rgorZHI0hUaKaMioyFIKMeHWJjFuVuWzWbiHSoG4yyJZBKkg
iaNHGWQrkuYUU/zODb3rFFv88uGdS6mttRMkqViQG3rXNCDf/fLh3UdKZLz42RQAmgqeSTGXVCnfey2l
kCOYSrFWVEIiqOIdDSrPMiE1NPCE8PY1CAnrBdEXUAkyK3LleZruzqI5XTeR+mVxQZnRANMBw1Ut6I8i
J37zvxXXnK0ohxt6p4zmGOmpHVIzy+piq8kF0zFbLoHxo8hsFDVu6B3u3ERrxG2FpyxbXQNzeUPvrlrt
IRLC6drugpHtBeqyw6GFy7eCuo3bLPjORBc1ShvkLBjK4i7McrX4qImmPp5ZF9z/BaYt4u67eEPKvK5U
oiVVisxpsU0suBIpDVMxL6f2CsbQKj7xvT8ldJrPvcDYmYKXrXHkCl4hgUEQavFOxCSln9iSFjIwtuaL
sTJuJxyZcBwgwWmNXFusRn6VPyMsVV1QeRxTpbqghSZpQT9mDRmRir7l2kIGXRNcl4NunSNbV6csptMS
EVM/kZ/8GYbGeI4jcLmIKufUZk5tENo5vZlzOZu7Rp2z6fkZZllFXovy6iWEz6n0zjuwDzPYL4+vcxYh
7PlTPlXZ6cj+2V7u2LLrVct6sCsj+wehNOzj7PS8Uxd2KuYrRtcmgOgC+o9CusY8VQfwH35HTU/F3Nvb
KFx7jcBDzFQax3wxYykd43FTFZOM2nDK7VijSPA3LKXvmNKoOZYuisavoGNjE/+X0IB4IWVKOyMXRcam
2Kq6gmsleMq4KzoUpYjtqBvR/ESWFMPeMBo8f3F8MHx+MDzuzcgxjQ/i46R/Ql7Es+nx88P+yfHs+CSZ
vRgOBi9C3KEZQnOH6eMdj0FThXaaadoEM0EOwm1NsOU7MccZR8nwRb/X70/pjB6+6L84mg7o7PhwNp0O
TqYn0+Pk8IAeJj3FlnlKtJB4o5soM6IUVd4I+o0Jc3FaxhX7N/JwePC8mWGkjHKNSy6vGlMJtYU/JjgS
/2nBlOXcFMOp0goDBTZjxi0QDQ6X8cMKhWWKsJTECxAYtqOhxvyYSso1LEVCVTjh8FYb48UQIWJeC1AZ
jdmMWXGrrg1VclOIn1O9AKJcKmJwxdRt3TXwCKUXVFGDiiiTr41gwie8B78uTAZhlttFvZwnVPbMwdYp
x62qa8zWdZBWNJ3Jtg4ZRvBgKhfNJSlooLVJu62RRu01390lMDJHy3VpcxsTX9lSPBrdIJwJ+ZrEC790
sjSlyy4wntDbrRgF59oj7zavKKbXMIa/fXz/U2iMrUEdVCJJS5xxav6lgbfRfhc/GQPTtYPmEtjPrmj2
0p2ZGSLoEPBTcXcrTYHqHmJ6bSfu7Z9SWNvCC18RTT7hZ3/DLgpv5DBuzigjc/rOtEJG8Lxyd2KR5kuu
RnBZk1ddesZ5MJ1StBHIO2i2bJqHzd7OUGxP67sMUSREty2WFPXrgRS2LSgsHLmBLX35diyzffCVEPDr
XH/aZRQrXBsr+vvQfzRGZ9sMVmVqbewjxIYK8hWxFW7UKzvt6Nlx3R8lsJfO6u7kJ94J8Hv0wFiMa8G4
73W9P4yJn00tfAcHJqr9z4gvSyHGqcH5dgm6rTzz9E+3w+PB81M4m56/ISwFv8xJLR4MXiMTvPq1UfPF
OlYT4QYYYHmt+93vfZ2Cg8rGFqtB6n2b9KMIfisF/lO+nFJZel/v0Sf1TpDk4r95VOjCMMSAsQsbTdnY
yhfHg9ZVU81hjEH1IzpHalntt3j1MBxTcyo9kALDUqWJzpUHRDLSW7AkoXzsaZlT79xF1PUg/FZ75ygh
8E0EjmzsQycoYIsWVaf90MnaFJZbLIbVLufOuuBdYnB55QUPKQ+yuw+eDfURiSTrbY3p7lKZSggnpDm+
y8t+FzoYynWu3Ox90Zh44nc2/hL0VCR3nSAU3O+YHlSnC0XzrNv+lCGK4JWrtZnMF8hU5BpUZt6eqEpp
mOqpEFppSTJTIE5ErKLD8DCKi7cAKiqW1Xu1OPoytRdoDJ4D6k0Nf1D/2lNLr7bYJA7jTZAQSrH2n/h6
wVSAAQ3u63e07ARBiLBVn4jrZy5Fqh1lHcQpL0YfDq0Ume8lTOGGidcFVL1giydOJYzd6jBesDSRlPte
6HQ5CEmSGL79igTqaFIypWkrEtRpl82by8/43KuvFfyV4MhapZ+O18akZ0s1b950t8cWczOSKtqIJBx7
oaRLsaLbTNSh0czbvdusi+GxwglN4P3fvZbQpUagMXxet941K29GRjlGLCas+JnMqW+OuQF5DzRV9BEU
YbqBPoQmjyfrpVhmuUb9JXcKuBgZf+Qk36CjtZtFkpIDS33XnWhRvbNlmCd+UQsPQklJcudv3WPzGkNL
RlfUZDOYfaOLQW1XjRS9ZLdI08MwdHr1JCTX5Nb3Upvqm0Q69boV+bk6x6heE9gYLJRhLuuvx0qNbKoG
SanUPk5UspbCvJVdzb8SnqQUOFmxuTVQxrC5hyVPfC/kZNVLGb/xjN3zii78JpNa1Qsmq9AUNP3fPEwZ
vBHQVWg7ByFL7ivCx7/uFRdJktcryjVyTDmVvpeJDHlDVdjQ9oqprPIAY3sCjZOx3bZa3pgFtWY6XmAu
blt3mkxB0ZTGmiYwvSuKs+GmONO2hePWWCkTdo8N16hxvmdDfEegubc40HyF8/7V+xHM2C0wDUrAmoJa
iDUUyuOsQ9fUju0RQ8de7Q74Obc0o30JQGBuz3RHGZWnSbjjChg6KscmbgL4rTyOvU2heV5nyBxiAF++
gLfqZSxNVW8hlrSnydT1S3AZ5rwuvbQ14TmtyMDMPn1qoEJNplVxFGO+hyLwgnrLY8sQFSdSOcQys8Lz
rJzdthEzUNXspizdM27eLW7evlb0eK9SUzIKXQrChTJGFptb6nTApdC4Xbem8yikNgxBVQyO/9oZmm/V
/oKJcc0M7hJWq5xbR2/ogERw+oZv2DcenKW0qHOWwdl+uag84wpcfXLb+hXZYMVprIiE63/dLtClPwnn
VP/t4/uf/OrD7X3wourC7u7A2rLhm7BhY90EN/y+wijF1lEbNNwHJpXZWPjbLuywoBueTC0WZlTHiyZr
JlEqHVPQJM84fou55nKiZ3vwDH6mcibkUiE2TaV5QWv7Q97rWxrn5iA/GPl4JroyF34PnkWbc6a3NLbL
q2/9MGjFGSfcjg3cbJknCEnG/MA1YOzjuESSte9Ii+CTqyab7ZRpDooVlSRNHT40D3mamm7zeztTPMA3
0JWtq6AbpqrAzqWpfGkeiVXg39gZcFP1Gv4bkSZU+uhClchlTLuuxljIwCULG4CiHBh6wWX/yp0DvDFP
w0w9tEQ/ExKkWENCtcl7qwK3T8n8pGJA/pn8E5i9lUKyOeMktUG1e/tietgLiijLi6BND9uzkTh+2R+D
d5adn03PMXzGtPpsKqNz1KztZn8S2jbFPnhnUXbuuVzFFAPCSkkavmu+jKhs5W0PTs9fbRZvaGgCuvS1
+ubUbyOyQklQuaXldlFBxH2FfHfaVu/D4ggeYsSQbcAMyZmk52dIwe8nvJWGdhbMRmeR2bTBj9NAfasb
7Z6mkdroaEWrjAYpLfNY5+anHs7FmXpEtbfj8reKl2JJvbtRdmde0VU2zCBhKsYbfQerw/ZmzWP6GvGC
xjfKaPeUKBZDLDjeDvcgwfSkqhtlUmgRi9TENLhKiSWFGy7WHBSNc4kL15TccIoZUFglB3d8SWw7p9HH
GmwNbWQw2C7ZbDpVmRCzj4QzffcSOfFXh/3BQdBSAWoK4wdQZpmVAPK6JDdopswDDGJ/osKpXgt5A4rq
PAP8aEWlcFtMNVv2Kbtjw/6w3+sf9obDT4Pj0WA4GhyE/cGLw5P+4HDwj7allCftC4/DwdHJ4Png6OCk
dWFN1VtFWTbTvJFJ07vtEO6WIBUw4d7XCjKVxprdG1e2V9kc2Fs+E7sJJIdHU0qnJzshNlqxge3uhizU
JCOol59TDDj1QwvceyBHpfcQKONKE64Z0TT5YceBH4bD4+eHJ4MXw+N/PIQLXSFLt0mNXMet4DVsbw2U
eH4l6m2FLHfWj6zs7izP3tc7eXuVl1UmzwfGZ6KMicto9rORvivOmLqS7ZpvA+LVrAFWfU6530vBV1Rq
vKqYe5cBbUxUtWlY/gLoxnRhEV1peKq+xyyzrbY60OWN68jdN8LiudAmSLQr3Y+rMHbEpWbQK6ndhF4Q
E97RMKUgKeNMk5T9myZdzBY5pQmyk1ClpTCJ6xIdqF7QO6C3BZMm96pEY9/Z8KqWfm2mwzilRPpB6LBW
K30o9gqoFxiX6XtewXAh67ec6fJBgotYi6BnUWlDNiPU3Y1II5/2PuSg32+p5g6b1dwH2pQYZzKptJs3
z+s4dOhtRnjS6dnS1FdaCPYnD+4xRccZwl4suJYi7bQYNEOpacCObHGwzekQTXabRPcjEffbCdy285UW
yUcaC544NkeA1D6yM2IY+/09yygC+GhyrBGgGwEhgQv9+Gaxzh9oAtb91yNaNLUFD7XV6kEgUv741trB
jp7Y6d63tOVMc+30m5thmL+lYm7jjeK9iaToF5JqzeTRjbH5V5uwxus9Qvgb6Ie6ZIb40io3/xkrjWDW
jcb07Ss0119HXaAv1/GZgHFl4eUG49VuDGLubH9rQ6uKPHTOuVsfNb4s+Pamqdn5d3Somy0toyIYz1Ot
IM+MPlh7RxPjkKEoAu9VflmuRlG0Xq/DjXsKOdURvSXLLKUqIhmLpFh/dubPuIe2YkR7D00n4Zbd3P3T
YC0rvaQ4FYoqbVtU9d8dYRI/Lt2OaWzVfiCN11yKte0KhUx9XIg197ce3RcCQ3ToH1LTJjDlReiB2R9Y
/TptsC5YQpvPSHS979NRuG+V+NbGShTBe9xSO1raN/RdhQIHbLsuCELcoIWIsn3WQkGtYlmv6BQCrWS5
LiFFkfruPfCmNBXU+ajUrLZB23/vUQA6m9yKFvXMzbcVvLbuS1EBa0VdlsTq1DyL9u73/icAAP//aKij
5XJCAAA=
`,
	},

	"/assets.go": {
		name:    "assets.go",
		local:   "assets/assets.go",
		size:    0,
		modtime: 1604572080,
		compressed: `
H4sIAAAAAAAC/wEAAP//AAAAAAAAAAA=
`,
	},

	"/details_close.png": {
		name:    "details_close.png",
		local:   "assets/details_close.png",
		size:    686,
		modtime: 1603364414,
		compressed: `
H4sIAAAAAAAC/wCuAlH9iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAACdUlEQVR4Aa2V
30tTYRjHVSgsoQKhXPUPlKZMlImiIIg/pggiiDeCBAdqyC4Kf9zVhVdeelX33QnCbtYvxZsxxkoqKxiz
1SzdFudMb5xO5/bt+fa+sPCw3IVf+PA+532e5ytn53lfK0qoSrggXBauCbUKxtxjjjVnq1IXXxFuCXeE
FqGdMOYec6zRtZX/M6sWrgv1hmHcDwQCLxOJxM9CoZAnjLnHHGt0bbXdVG1cEm4KLp/P9yKXyx2jhJhj
DWvZc9qUwUWhzuFwdMVisc8QFQ4PcbCygvT0NJLDw0gNDSH96DEyfj8KmQwo1rJHem8oD2VapX/sxlAo
9Aqi/N4e9hYWsDMwgARxD2DH7ZZYren5eZxYFqhgMOhnr3BVeSnn216v98Hf3yqXg/X0CX719YFs9/Wq
uJfPGtkzZ2fBWvZ4PB6DHtqrokaol7/0GqLM2hq2enpsxMmpvf3VVVD8UOJxV42Uet1Wy7J+M5mam8P3
7u6ySM7MgDJNM8mRUl5qYDtOREz+GB3FZlcXNjs7UUrMk/jYGKhsNnuo57TWZhgTw0hHO0EpRdpV/tvI
CKgjUdFQv/Lu7q7JZHxqCl9dLqGtSJtL4VJ80Wvc8xD2V9YfRUbmLZPp5WVstLTYaSWt+lmt1tISKH5Q
/VFqbGOTl6GNTk7iQ3Oz4FSrU8UfuTqdBJHxceQz+2APe/8Zm+Jgh8PhNxBlt7YQNQysNzVivbEJ7wXG
iiZEJiZwEI2C4mFgr/aoKnn0jk0TiWfPsTE4iHcN9xBuaMCn/n5sLy7iKJk8ffTqikfvfC4H9laWdX2l
UqltaDEu9/o664LtIOVfsOf4L+APb5yaiwyN8+8AAAAASUVORK5CYIIBAAD//1c8bPquAgAA
`,
	},

	"/details_open.png": {
		name:    "details_open.png",
		local:   "assets/details_open.png",
		size:    709,
		modtime: 1603364414,
		compressed: `
H4sIAAAAAAAC/wDFAjr9iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAACjElEQVR4Aa2V
30uTURjHnVBUgglCaXVTJJVLMdhQm7+1JEvJiKAggmgSQiKJl0V0E13UVf0HQZmBLcvlpqa55tqV0YoM
zIhY6js0yDH11X17vuO8Sq5Zgl/48DznPD/G63nOMSmBkoUNwhYhTUgn9NUeY8z5p0wqOVXYKRwQLMJh
hYV7Kpaqck2rNdskbBPMdrv9osfjcQaDwW/RaHSR0OceY8xhrqox/a3ZZmGHkO9wOB7ouj6PBGKMOcxl
zcqmdDYKGZmZmSWjo6PvIYosRuDWXGj50IwTb4+hxleN5sAVvJh4jvBCGBRzWSO121UPk3EAaUKuz+d7
ycTp+Wnc/nwL1d4qHBVidmjZv/npBkJzGiiv19vFWmGrcVDsvKupqeky/056VMf1j9dQOViBKo9Aa/ix
dbnYcrQGWsBc1jQ2NtrZQ/VKShHM8kvdEPVN9qJsoBRl/aUoHyiJ+UpcCxJTtmfCDYoHJT2yYyOlPtca
CoUmGGwdbkVRbxGK+2y0gg2GisUvNmJCy/BVUJqm/eBIxXqpgbUtiBise12HQlc+ClwFSKRCiZH6wXpQ
s7OzETWn6XENa/trYemywuK0IpGsTotgRU3fcVBzouWG6pOnpqY0BhuGGpDXeUjIW7JKcfuX3tjjP9k4
FBkZN4PtY+042JGzzNMcGDJ35C7tmcU++tJmjE63OpSUuLEJ62GcfXUO+59kr8rJnlOY0WfAGtYaY/PH
YPv9fhdEY7++4nz/BWS17UPWY0Es2avWp3vOYOTnCCheBtaqHskJr95kZBL3AvdR2XkEex5mYbdQ+qwC
d97dRTAcXHn1Moyrt16PA2tN//V8jY+Pf4cS/VWerzU9sDay1gd2Xf4F/AZqlpeB9836LwAAAABJRU5E
rkJgggEAAP//wNSxe8UCAAA=
`,
	},

	"/index.html": {
		name:    "index.html",
		local:   "assets/index.html",
		size:    6155,
		modtime: 1604572022,
		compressed: `
H4sIAAAAAAAC/6xYbXPbtrL+7l+x5Z07TuaKpPySNE0ltc2Lm/Q2L62d3uRTZwUsRVggwAKgZPZOz385
H8/v6B87syAly7ScpJ3TmcYiuNx9dp/dxQKTL569eXrx4e1zKEOlZwcT/gMazWKakEl4gVDODgAmX6Qp
/GhXyix0CyUaKRwWgSTMW3iFLigDL6z2Ac7XZCTBt1Xpu1/KwPH46MsRNLVE/iIuHI8hTaPmigJCGUKd
0m+NWk2Tp9YEMiG9aGtKQHRP0yTQVcgZ4NcgSnSewvTdxVn6KLnWYrCiabJStK6tCzvfrpUM5VTSSglK
48MIlFFBoU69QE3ToxH40imzTINNCxWmxiZbx8+FU3XwgI7g8reGXDuCubXBB4c1oJEgMWDAuSa/ccvH
b8A7MU3YO/84z4WVlHUKMmGrvPuZnmQPsnFWKZNd+gSUCbRwKrTTxJd4/OBhevX699fHeKrD8snp6SuR
//D7SX1xqt4diYp+Hp8t3/vT2jX5D1f40zQBEM56b51aKDNN0FjTVrbxyWySd5juhOcDimWNocy2zglp
ItLtQn6anWZH+aW/XroD+cmj03RdnD87O37+YPzh+NlR805ejt+cNK+e/GAum3fPTl+WX35Y4wd5pH4r
luFy/M7KR98/fX6lT94sHqli/eRh8tedyXPGfM1HZijkR9nRODseM+w+/Cxw0Qn08G+qZNqfnp+DI28b
J6gj/5p0SQU2Ooyg1o3fpb9/sUkDrcwSHOlp4kOryZdEIYHSUfG34i78MPDC7438L0trH12dPv3evzn5
nxfl1erRRf7Tg7f4Piz/NzQPm8WDizf0+peHiyfqjP7v7fdnr7961ZRviuOTn756WVyWd0f+U159lADG
v58B9mN2MMm7jnMwiYrZWOao1iioov8/gPhfhVddET+Go/F4XF99fQDwxwFAkJmkgEr7lEvfWQ2bb+Yo
lgtnGyMfQ+P0vcO8l/zV1mSy2iwO74OxqaOaMIAgE8j1f77udYjGeeseQ23VZjladZkv7dr8PfNCW0+f
tv/HwSTvQ3IwmVvZRh6kWoHQ6P00YYuoDLm00I2SkSeASXk0e6FWNMnLo9mkdHm/vPOhs+teeKhQp0fb
NzffGVxBoekqFVY3lQGDq7RWWnMqymnSP6QB5wk4q2macC4oHxJApzC1TpEJGJQ102RFLiiBescWwAR3
bKUx31AEtaKbFkpbUWeG0ykNdrFga/xyk4//tSu7A6eH0jPlb+rsX3rSJALJaRJcQ8nsgnwA36hAfpLj
x/HeBOrINzr4z8Xai38O3K3oAHGB2veQ/yrYirzHBX022o3858C9lt2P97u5bcINvJNcqtU2Q288DNN1
fEe+Bpyn/TBwK0P7ceNm9g2+rdEQFCgJuNLvzMQd//kL3fuocU5ak5y3exJ31yzX6/Hs+RWJhgelwNT1
yVYeDwTr2UVJnnaE4g6FK1Sau+ooziUCDcwJtEVJMoOnWoklWAOHP1qUhxBsfAUIghy3jy65s0le3zL3
soDWNp28pxU51H0pjOILNiVsVTMKZaRaKdmgjvgEevJsVqqiIEcmgGuMz7vPc6G5G/jbRuMGssODJoj/
pnPrJDmSHQWF0hTXeQ+PP25wuZsxHyV3b8X+BU53a/wuWpU10Ms9homv0USjWxZ/5Rk2mb22oVRm0RMH
LYVJzsKzvZmwT48kLz6qZ3+wWQldkdh6vyf6PjhVc34OuOim7ORoPP7v/ygTe9rLp6i40cFucxGbDPQb
4+14PqHCOorvR7AmkEpCiSviA4Un4xufxkDzIQIqVEa3ENYWCusqPgCADxgoitxQDbEm59qKpSi52qII
3GsJSwglcf3y/1DQGirr6H4GF2Vf47Dm9wsy5PgYNVC8UgioKZQ5CxMfcNhW3QSuOwRHtfUqWNdmcOZs
BaHEEFdHoAKs0QNd1bEVDzRHwa5EIRBWHlTFxysG3CNjS9R1LVgrzjh+qRzwVCQaH2w1VEo+pCU6Q96T
39tvXtv1qDMulTSHAdbWLYF5q8kVJIJuY0O7xtXLoV5j66FutIYOycC4RjYPPYUMfl0Sh59lW+7uDWrd
blySu576OGsbLqY1Dtk1lqcDRxk8U7JTJqxzESusyKmiBe6cbSzKb+BlH3hfk1BschglZxsekG1FDNFA
iU4W1i37ZMC6dhYFK+v8SKyt/QhKamPeCltVPEEOKeUgxhC8fw9zEth42iRBgUors0j2UnLBGN7++S8e
Tc9/V/rPfy5aBfe+XaJDrsL7UCL7rTwoSTji/cU1ps8eD8GGGNi5RrEcYJrbqww+2AZ8rQw0NSAYG68P
vJJcE9KKJY/Emzl3xFXmQgSuQrmH585sGqNbKMGfFqqPVEEk+VOmNhakz+A7Y2MWDC0N1B5aJ0riE1gg
f7hNjk6vtGvDzdbHdTJBue51rDUouPQWKpTNfKD13q220NuPin7+8W3awbyfwbkdARZMAvold3eW2FSo
HejdKdZOwQhQ6/i844h1h2CIGLYFaUF5iKc0SNYlhkPPO7zbX0ZR6zdJ536f5CoALpTxnd1NYwGNPkTx
Lg63GdsMC3dkn/XbOnRcEcjNjcBYV8W8CqiXHjA291gvvMABiksDW0mpVtT18SSDF3bNlTmKTZ/dpxWZ
2IPZJ49B8UjllREE2OXJUN9uNJM4DkkLtu8ryiziztA1BTTgyUhA04KhEDtbv2VFiYHqNUZmYzC5KNLG
SHIRO2cDFOhivaP2ttuouijF7tlTwr8Hagv0IfWtEZsxkRurdRXJjsxeiQVRklh22hhCfVxzWmmqNoe4
gWJpycdmWOEydpbaeq/iABGz65k97zasqtZcmVEHYAgY6/CcPWWu0Q0TpPNwS1wG+xJlyyUPRTH9OX5S
+aCMYFOPNyzHDZy3ICN4YIZgrb5dQpNGzwZL8Q5kttnzQnfG0mq/mDKMBJtgq3gBusZ2dLd0cIThZlXH
fSc2TW6TFB8L5PLfRjbbp3CSD5HfDtd2GmJzz8+6yHSOWbd3OjqzcaOM1Qz/OIGW0PmYfzH1ynieiBx5
cityvAUYdkgZqJ2VTeQgG2DdXIbxhx23FEpJK1v7TNk8482SDw1wfJp/2eVnv9EXFLjwekz87Z6u4ruW
E7d5aqq8W+OenH0qQJtLk+uVk9kzmjc8VS8meXkyjJDrxmjJMjwI1+5jY/Bdx9vtz/7HJO+ufQ7i3WQ8
hrHHWNfxrnFzCRramvrL8ktcYbea9HejWNeDq85J3l39/zsAAP//qRsA9AsYAAA=
`,
	},

	"/viewer.html": {
		name:    "viewer.html",
		local:   "assets/viewer.html",
		size:    2723,
		modtime: 1603658490,
		compressed: `
H4sIAAAAAAAC/6xW23LbyBF991e0R5Uqu0IA4k2RIICp2LGcOJZkO4pjPw6ABjHiYGZ2psGLt/bftwYA
Seiy+7C10gPJnr6cPt04g+TlP2/f3n3/9A4qquXiReI/QHK1TBkq5g3Ii8ULgKRG4pBX3DqklDVUBues
PSBBEhelkAhrgRu0SdSZDlGK15iyAl1uhSGhFYNcK0JFKfsHuJpL2YdCqS0QbmnvMAKhnBEWC8h2sBRU
NRk43dh8X409rsMbqrQdlKi0FDVXnaMUagUWZcoc7SS6CpEYVBbLlFVExsVR5IjnK8OpCjOtyZHlJi9U
mOs6OhiiWTgLx1Hu3NEW1kKFuXMMhCJcWkG7lLmKT89nwdeV1ufb2dv37nb6139V2/X5XfR5/ol/o9V/
qDlrlvO7W7z5erZ8I67w/5/eX91cXDfVbTmZfr74d3lfMcitdk5bsRQqZVxptat147qu2l78N4BQNXUc
Z1hqi/Bza/J/PRsxcCL7SgqFry/bw18OUUfnTNsCbWDFsqJ4bLbgtBQFnBTjYl7wy4PfRhRUxTDF+nJQ
SGobg11m/NXkb6PpeDSdj8Lpw2q5Lobg9BptKfUmhrVwIpN4TFdqRUHJayF3Mfz36lorHXzBZSO5Hb3V
ymnJ3eijyNByv1ngHUbXqKQe1VppZ3j+OJsTPzCG8cRsn6A+mcwmF5NBwEbbIthYbmJQ2tZcDo4qQRi0
BWIwFocNkg0rsaykJxCLQacZz1dLqxtVBPuSZVlmRTGMPqm5UMcYw4tCqOUQcu8nNS+yhkirQYl+KGf7
ofSIeCbxMe/Po7l8tAcx/M4K7FeFF6JxMUyHpPZIxqenfxlCKcQ69LKC9oik5nYpVAznZgun/v/ymfbP
hsl7c0DatGFPTzJNpOtHh8+1fFael/yPdE3aBBJLer79gVP7JD316p8GL3iB39bBaP6MvYeXojbaEld0
rJdEvVi0utEqMjibH9XP70h4/1ODdtdKXvc1mIbz8LRVuPsnAjeZnwXbmx83Ez6TtHozm13n0YcfU3M3
E/8b5zV+Ob1afXMzY5vow5Z/Tn9bzJKog7QYoKOdwZR5kqJ7vuadlXWgI25M0F0EHtez8aJIGW55bST6
JGyYsNSadbp5VwkHwoHTNYJrvdubKITvuoGcK/BPGyjcgL/rHKwFB6oQpCCSCEKZhoBneo0j4KoALp1u
M+8dGytDeBcuQ2B/9ynSrkpIW2JdCK5RQXtDkQbDLYncD9yb0IUv2mxSrPBpgpOP81PWTbfvP4m6qzvJ
dLFr6SjEuuXCq0vftLct+p1LSm1r0Mo1WS0oZUeu4xIpr66ExFevLy1SYxWUXDpki8O+ttlzyZ1LWUtF
4J8yM/AASDqOjvSzfYQvHfgrymrJwEieY6VlgTZlke+05agF73/5QbDoQebnqwfcGFTFAxAASS+ZHY6u
3S75UU8PyDJSkJEKjBU1t7tHqQCuPDWPbEM0PiVaBlZLX4w4NY4Bt4IHlSgKVCkj26Df3MEs+jxRB+ZB
pw/dHvxMIs9jP9njwRBOp7v9O9dBdw5dJc5w1S0JEmeLebd6ML64gDdJ5E8Prrz1s3wTNFayxRe+SSL+
tHh78ezLe23pqN6/vCVR69AuaBfVL2wSda+kvwYAAP//0Gc+kaMKAAA=
`,
	},

	"/": {
		name:  "/",
		local: `assets/`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"assets/": {
		_escData["/app-viewer.js"],
		_escData["/app.js"],
		_escData["/assets.go"],
		_escData["/details_close.png"],
		_escData["/details_open.png"],
		_escData["/index.html"],
		_escData["/viewer.html"],
	},
}
