// Code generated by "esc -pkg assets -o assets/assets.go -prefix assets/ assets/"; DO NOT EDIT.

package assets

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/app-viewer.js": {
		name:    "app-viewer.js",
		local:   "assets/app-viewer.js",
		size:    4520,
		modtime: 1603658490,
		compressed: `
H4sIAAAAAAAC/6xXX3PjthF/16fYIDdz5JmmYrdP1uk6zU1uclOlk4mdp6YPELE0YYMAA4CWXY++e2cB
SgRpy+l04gdZIvb//va34HIJNw0C77oCWmMRjAWFzpXwTwO15S3ujL13oBEFgvENWvAN18DBdYq7BkwN
d7/3aJ8WD9xCw6t7B2t4XgAALD+Efy2/x43UCJVF7tEB14AKW9QelLxH8A2Cx7ZT3CM0aPEq6AHAR28/
Hb7TLwFSrNnm+RkUGdzvGVSKO7dmum9ZeLhm4ymwTx+XXkxNfHp+hspoT+73+8n5x+XB34flJPQrqHtd
eWl0pvt2i7YAj48+HxKlP4UevIU1CFP1lFsZ0/0hZpoxb1k+lRYXb4mLRNyLi9Kh/7v3Vm57jxmTghXA
NgzOoOPW4Vfth9Dyt9RCtUiT6vWWIFWQFW/Yjhlc/u8ZXJZSa7Q3+OhhHco3HtqSdx1q8bmRSmReXOSr
04eXyaFF31sN3oYn+2IRgbcEh/7HDX26AK9G3jZK3jbRZzic9jRt5buMlUcFFCwvLbbmAT9T8TI2OVqR
M9N72EnfBFdGidTSt6FH5KHsuKXC5CUX4qQtqUdTGnfzvJq+5RoscsG3CqHX0rtwFr4lOSlTzeFJIrAG
9j07PpY1kCR8govvLv+aKgQlU8E6fC7D+eTwYA3+kdjb/5mWf3rV8NByZarSmy/yEUV2mcNZ0Fq9gEFj
dgFxQhJhPTngsO11FYiLMAhGh1JLgdrLWqI4cFNEyqCfFFaY9qsoohV+8woLVEbgf9K5uEU/DMX3T19F
NDAdJJo24s3RaOk6JX3GftPJENXGQkbyEtbw3QokfIyqpUJ965sVyLOzF6VGH1KCdaTn8kBqmYQzuCii
hX/Jf+cTtZDFZPLISP5KQ2iJUCWpVlLfgjAaC9BmR67fO9hJi9B3ocy3vfdozyslq3upb1MbzhBmeOTu
SDcgHQRRFEUqelHCzxYfpOndONkkHOdUpLKXZVhxwapMxGcm/xLFpCAhLgQK8CaE/OsvG2i4ayb0EOiz
NDp7H+J7X4z4MNu7eQti3QPrZO8y30iXl9x7O9BsPq18I5039qnsetdce+4x071SBcRP9i3xydSKFCxP
SHGfrxZpbtfooUXPz6WuTTkBHj2mQUxABGfAgPDhCiBXMfhAL1mCzyiceD0Fd0Y+WD5hf3r0gsTTICZz
TMC67oJ+Moeuk3o+ei5KwTowb8ulhlIZLtCyJNKDZODgMHdsUDzfGivQwvTnuWvZakJsc98hyqgzknvi
Im0OoHJ4QjfdMyfUX1l0n4fbDNWJCK6WCuEs/KOOJ1zYKwFbhIorhQK2TwHgsUAF8NpT6n1VoXN1rxTU
6KvmsDEHL0kHiD+L4EbzFtN6nMTCg8QdNSOi4cebnzZU/aS6ejNQ4TAzA/8eNYeL12qOb0rE8h0IdP6P
w7B8d95bxfLZraexWLMkpeM+2S8Wy2WsxxeqLtXMEalxWtKx4t4ABbk41GcUzwL7LD+A6eiAK7jr244U
wsGHJRyKF9a0VQOAySx5Ynn5wFUWaWIszDATmbf9IdR3Jb/jj9nYid6qK/oYyU5wz2+eOrwCRqVk48nQ
+nTXcc9PkFniv+bKYdKSQyIadw65rRrq8d8omTURSm/VVJYmaie1MLtSmYqT53JQ/GY9WpkH8sdcOapO
He4nv44o8dIrhPXLAI/8PcxAqEtBcvlJnqfO5i/SDE9fyWOePi0cqlq4PJLSqQT2Y/vQWpMS5N3vBTjP
fe+KePb/dZIrtD5jX7hUcSkSImFoJC2L33T0ckXP4tf4OAZET6P71TxqWlT7xTgwmj/IW2riIdLlEj43
WN2Hm8/kYqDDTo7LjN48dU8XHGp79PIapoKG67fO2+yigIsc1qHEaV2ineNrz1smLg87d/8y1kAIRCHl
caw7bnlLzEaE8esvm+uAzJ/D02yG+3xMIqrNF10dg+StI27LGPlLVxxp1vN+v0IpdX4CETPSZRvDBV3u
SL8sSzYDyUh19KYzPTu+o/X4Yo8tEoEAvgCId9lhJunVi4un7AjqQ06U4DcjXtJUaSM0hlZBzXvl4zV/
ixXvHYI2vqE8dtzFxSfGC9HJ7E/uEXzkbacw8Giy0ya4GCDEhfjhAbXfSOeRZu19ZzqaFkwvjzk8p1MQ
BiRfLf4bAAD//6qI6yuoEQAA
`,
	},

	"/app.js": {
		name:    "app.js",
		local:   "assets/app.js",
		size:    16468,
		modtime: 1604511872,
		compressed: `
H4sIAAAAAAAC/7R7X3fbNrL4uz/FlNtfRdYSadmOnchRurv589vspk1Pkp6eu05OFiJHEmIK4AKgZG/r
5/t2P+T9JPcMAFIkRTlOt5uHWAIGg5nBYP5CqRTagEJd5ka/kdLAFILEf0+Cg4PS8FzDFH45AABIvrV/
4Fv4y7vvX41QpDLjYuEHE/t3aVb5RzuDE5iXIjVcilAbFXkkFlHyCg2YJcKz199DJoEbmEsFpY5rmDVT
kMEUMpmWKxQmThUyg89zpG/hwOC1YQrZILqo12QxFwLVO7wmTrRRF40t/wv1EF4OVsA2TCHIeWMOlsYU
kyTRhqVXco1qnstNnMpV8s8SNbGgk/Hx+NHDs6OEOKx5H3Ex+sTWTKeKF2b06Z8lqpsm4pfwqdQGMikG
BthCIW5ZVGhKJSqqSaaO3tvhwYFfjiJlhS5zZhAyZhhwoXmGwMAwJ3jDFg1Bm5tiCL+/tM1NsVfMYRDA
od3zYpczWZpezlqaBH8yRvFZaRB6dYoZoz6rU9f7qQ+ugwZt17FGU+8YBrNg2KGehMHyHKZw3WWgwRzL
81iXM20UF4vwbGgHchQLs4QRnEX7OH7GlbmBUuWjginNxQLk3J5OqXJYMr0EjQuiuyWDBZqPNPmxYIqt
dEMOTSEQ5QrNmhHxv9y2xq1qwhQ2XGRyE+cyZbQ+JqwNRsYdQayZIgtgV8e6yLkJB980Lx2pUkiQHKZw
dAEcHttFXhYXwA8PmzRWiAvGFUwt6CX/UKGeNlF7aa9ZfpkhHf9Pb14+latCCjpWQnB59CH6QCe/Z3r8
Iaqx3XZP0KHed05PrQ5pYAKYSJdSjdDpE8yVXMGgFEaV2mA2gJyLKxjQ/RzsHBrNNU6rVPkQyHZ1j43d
YetaRo519HepcB4MSXtaQMbdTvqzq7o997Ki95PukvxJ/2coDraGc0Im5JP+txjoP77q6+NZaYwUYG4K
nAbuSwBpzrSeBjMjYGbEKMM5K3MTPHnmPjxOHOCTnVN14w0hSZHmPL36ckk5THeJi0gmcXmi74C07FhQ
z1Ch+IqpG/v5WgdRR7xPpTCk0F0pd/F65oIh+E/RvQ9kLtWKmY+Gr1AXrCmxbDyE7LgrqozP5yStYxhB
Nm6boo9kiIJgO8jnENoFj+Goa2Ic8ChoWxOPfkR/L3osQ+UHv2dmGc9zKZXbIIGHZ6dH9K/pB2nm/03r
qTa1y140J2f7sPiZNpJVL5KzPSjOdhHoXgRjt35XSeE7CDM4hCALIpi0hM3gcAphyODXX2EZEeCSAJce
MOqHXFnIFUGuKkgKF2hABzsX+yNNsJ0waFmuGNlrlrFZjlAKbtzNtp8aSpXLtKkIpCC5TOExjI+OT7sq
4vckgEMI/hz06APNTe3/iUXxxZhjI1/wa8zCY2I7+Nufg4sv2WYvou8rRB3L9/y6wNRYryVnnzA1kPMr
rPG1yQwUFjKYQEDhr54kyYKbZTmzgS+aJSosV8lCjqrPwbC9PJWrFTeE4Oh4nJ6kxw/HZ8ePZmx+jAwf
nZ1n6fH8iJ0/ODnOsnmWjuezLoaZIt9KGBTmyDQm4/isexA/8zyvDY1ztkbakEnxxdJAkbMUgQs3hIV0
ErGAE7gnb4lRiMl9+XChN3moCfRh+6NHBJf/+z//DQ3ePhw0PYkl6Q0W8lXb5VIo0dVjGouJO5hO7S3q
VbmgV7/q9e7E7sRQ73MnIndw90NE+vpH8vANEmKd8xTDoyGcR/sMsY8A7o2H5p3AayBP5iEEHzp+46sa
bawNU0b/zM0yrG9CEO3hyqbEcSPNDa3HvyAzJaTxZ9rg6PeJmQxTCzTk2z/OciaumvY2SeAtGpdoWjnN
udLmc+FXzX8b008aoWBmaeN6Ym03JGMxAQi2Qi/9cXS/o3lfHp88PP/c6Xh2ZtIsHTtMZGBvp9feNSrN
pbg3g7SBu94dCqN7BJYHtwcHdLRsDVxb82MMuSDDc25uyBBpIxWCWXKx0JUVsmG+JiPFDBQoixwhZcLZ
JC7sqnI+jw9IKQh3XWNJIJcs8/Roi2zN8hIpSxxc4c2g2uKnN698VuasnWRZw4Jc4U3XgHz105tXb5Gp
dPmjzSG7Cl4ouVCodRg8V0qqCcyU3GhUkEnUYmBAl0UhlYEOnhhePgepYLNk5jtoBJkNuYoyz/cnYgI3
XaRhnZ9qOxrFCzSWq1bGkiRe/PZ/J64FX6OAK7zRVnOs9PQeqdllbbG15JKjAZdxw/ReZHby4iu8oZ27
aK24nfC0Y2toYS6v8OZDrz0kQgRu3C4U2X5HuuxxGPnWJe9R28ZtF3xlo4sWpR1ylpxkcRMXpV6+Ncxg
SGc2BP9/hWmHuNsh3ZBKgFslWqHWbIHVNqkUWuYY53JRTx1UjJFV/DoM/pDhrFwEkbUzFS8748QVPCMC
oyg28pVMWY7v+AorGVhb86u1Mn4nGnkvaIBFFy1yXa2T+NXhnPFcD0GXaYqacl5pWF7RT1lDwZTGl8I4
yGhog+t60K/zZJvmlMN0USPi+gf2Qzin0JjOcQI+F9H1nN7O6S1CN2e2cz5n89do8Hj25DFlWVVeS/Ia
ZUwsUAVPBnAIczisj2/wOCHYJ9+ImS4uJu7P7nLPlluve9aDW5m4PwRl4JBmZ08GbWHncrHmuLEBxBDI
f1TSteapOUD/6Dtpei4XwcFW4Vp+uKqwhAFhRmUd83dznuOUjht1ygp04ZTfsUWRFC94jq+4NqQ5ji4k
41fRsbWJ/18aILyQc228kUsSa1NcYVbDJy1FzoUvOlSliN2om9D8wFZIYW+cjB88PD85fnByfD6as3NM
T9Lz7OgRe5jOZ+cPTo8enc/PH2Xzh8fj8cOYduiG0MJjensjUjCoyU5zg10wG+QQ3M4EX72SC5rxlBw/
PBodHc1wjqcPjx6ezcY4Pz+dz2bjR7NHs/Ps9ARPs5HmqzJnRiq60V2UBdMadTCBo86EvTg945r/i3g4
PXnQzTByjsLQkssPnakMXe2IS0HEv1ty7Ti39VTURlOgwOfcugVmwOOyfliTsGwdD1m6BElhOxlqyo9R
oTCwkhnq+L2Al8YaL04ICfNGgi4w5XPuxK2HLlQpbS13gWYJTPtUxOJK0W89tPAEZZao0aJi2uZrE3gv
3osR/Ly0GYRd7haNSpGhGtmDbVNOWzXX2K3bIL1oBu93dcgyQgfTuGg+SSEDbWza7Yw0aa/97i+BlTlZ
rkuX29j4ylVzyehG8Vyq5yxdhrWTxRxXQ+Aiw+udGIXm+iPvPq8oZ59gCn99+/qH2BpbizpqRJKOOOvU
wksL76L9IX2yBmboBu0lcJ990eypPzM7xMgh0Kfq7jbqys095OyTm7h1f2ph7QovfsYMe0efwy27JLyJ
x7g9o4It8JWtpk/gQePupDIvV0JP4LIlr7b0rPPgJkeyEcQ7GL7qmoft3t5Q7E6bm4JQZMz0LVZI+nVH
CtsXFFaO3MLWvnw3ltk9+EYI+Hmu3+0zig2urRX9bejfWqOzawabMnU29h5iIwX5jNgqNxrUjVry7LTu
9xLYU2919/KT7gX4LXpgLcYnyUUYDIPfjYkfbS18Dwc2qv33iK9LIdapwZPdEnRfeeabP1wfn48fXMDj
2ZMXjOcQ1jmpw0PBa2KD17A1ar84x2oj3IgCrKB3v9uDz1Nw0tjYYbVIgy+TfpLAL7XAfyhXM1S19w3u
fVKvJMu++08eFbkwCjFg6sNGWzZ28qXxqHfVzAiYUlB9j86RXjX7LUE7DKfUHFUASlJYqg0zpQ6AKc5G
S55lKKaBUSUGT3xE3Q7Cr03whCQEoY3AiY1DGEQVbNWiGvQfOtvYwnKPxXDa5d3ZEIJLCi4/BNFdykPs
HkLgQn1CothmV2OG+1SmEcJJZY/v8vJoCAMK5QYf/Oxt1Zj4Ohxs/SWYmcxuBlEsRTiwPajBEKrm2bC/
G54k8MzX2mzmC2wmSwO6sM8XdKM0jGYmpdFGscIWiDOZ6uQ0Pk3Sqp2sk2pZ0srJafRp7i7QFAIPNJpZ
/qD9daRXQWuxTRym2yAhVnITfh2aJdcRBTS0bzgwahBFMcE2fSKtn/sUqXWUbRCvvBR9eLRKFmGQcU0b
ZsEQSPWiHZ4EKpj61XG65HmmUIRB7HU5ilmWWb7DhgTaaHI2w7wXCem0z+bt5ediEbTXSvFMCmKt8dyD
ro1Nz1Z60b3pfo8d5uYs19iJJDx7scKVXOMuE21oMvNu7z7rYnlscIIZvP5b0BO6tAi0hi8Ytrtm9c0o
UFDEYsOKH9kCQ3vMHchbwFzjPSiidIN8CGb3J+upXBWlIf1lNxqEnFh/5CXfoaO3m8WymgNH/dCfaFW9
c2WYr8OqFh7FCll2E+7c4ySBN2gUxzXabIayb3IxpO26k6LX7FZpehzHXq++jtkndh0GuUv1bSKdB8OG
/HydY9KuCWwNFsmwVO0HSLVGdlWD5ahMSBONrKUyb3VX8y9MZDmCYGu+cAbKGjb/LOvrMIgFW49yLq4C
a/eCqgu/zaTW7YLJOrYFzfCXgFKGYAK4jl3nIObZbUP49Nc/BGJZ9nyNwhDHKFCFQSEL4o1UYUvbM64L
ZuoC4O4EGSdru121vDMLesNNuqRc3LXuDJuBxhxTgxnMbqribLwtzvRt4bm1VsqG3VPLNWlcGLgQ3xNo
7y0NdDzCu9fPXk9gzq+BG9ASNgh6KTdQKY+3DkNbO3ZHDAN3tQcQlsLRTPYlAkm5PTcDbVUes3jPFbB0
NI5NXkXwS30cB9tC86LNkD3ECH79FYL1qOB5rkdLucKRYTPfL6FllPP69NLVhBfYkIGd/eYbCxUbNmuK
oxoLAxJBELVbHjuGqDqRxiHWmRWdZ+Psdo2YhWpmN3Xpngv79G37dLKhxweNmpJV6FoQPpSxstjeUq8D
PoWm7YYtnSch9WGImmLw/LfO0H5r9hdsjGtnaJe4WeXcOXpLB2RS4AuxZd96cJ5jVeesg7PDelF9xg24
9uSu9auywYbTWDMFn/55vSSX/nW8QPPXt69/CJvvfg8hSJoLh/sDa8dGaMOGrXWTwvL7jKIUV0ft0HAb
2VRma+Gvh7DHgm55srVYmKNJl13WbKJUO6aoS551/A5zy+Uk3x7At/AjqrlUK03YDCr7CNP1h4Ln15iW
9iDfWPkENrqyF/4Avk2254zXmLrlzaeoFLTSjBfuwAVurswTxazgYeQbMHZVnCm2CT1pCbzz1WS7nbbN
QblGxfLc4yPzUOa57Ta/djPV+20L3di6CbplqgnsXZouV/aRWAP+hZsBP9Wu4b+QeYYqJBeqZalSHPoa
YyUDnyxsAapyYBxEl0cf/DnAC/s0zNZDa/RzqUDJDWRobN7bFLh7ShZmDQPyj+wfwN2tlIovuGC5C6r9
2xfbw14iodzWMm0PO3CROH05nELwePaEYmebU8OhzxINW4SDYjCELHatgzrtjxvFZ/iq+waigfTZFo5w
P56ppJG0e8DdJwWtDaIexDWa2wZR/rSc3saVCO8mz8JY0gqFTx7T7vcjsHezHlITi/JxQuh72jjm2nQ6
Ml07slWjxsHbQ9ZGlakp7WN+74VsyaDZfvEpVsOR8KzdgKgbKM9wXRwXkHGd0qW7gfVpfz/lPq2HdInp
lbYKOGOap5BKQQrs3wzYtlFzo0JJI1OZ27CDVmm5QrgSciNAY1oqWrhBdiWQkpS4SQ7t+JS5jkun1TTe
GdrKYLxbVdk2kwop52+Z4ObmKXESrk+PxidRT5GmK4w/gbbLnASI1xW7Ikti30gw90MEgWYj1RVoNGUB
9NGJStO2lA327FM3sI6Pjo9GR6ej4+N34/PJ+HgyPomPxg9PHx2NT8d/71uKIutfeB6Pzx6NH4zPTh71
Lmwpea8o635XMLGZ9LAfwt8PogLei+BzNZNG78vtTSv7C2Ee7KWYy/0EstOzGeLs0V6IrVZsYYf7ISs1
KRjp5cecYkJz1wL/ZMdTGdwFyoU2TBjODGZ/2nPgp/Hx+YPTR+OHx+d/vwsXeSue75Ka+KZYxWvcX72v
8fzM9MsGWf6s71l83VtBvW032w4aj59sKg5czGUdttYB50crfV8/saWfrXdqA9LVbAG2vEq131Mp1qgM
XVVKj2tHmTLd7OvVv/O4so1SQlcbnqZ7sctcN6wNdHnlm2a3nch1IY2N49xK/xMaCu9oqR0Mamq30RGk
TAwMzBAUcsENy/m/MBtSQicQM2InQ22UtLnlinykWeIN4HXFpE2PGgHTVy4CamVI2+k4zZGpMIo91mYx
jsTeAA0i6yzDIKgYrmT9UnBTvxnwQWX12nHZ6BR2g8j9vUIrn/5W4fjoqKfgetwtuN7RSaRQkCtt/Lx9
ASdggNcFE9lg5KpHn6nyu18l+PcOA28IR6kURsl80GPQLKW2Rzpx9bs+p8MM228S/e84/M8baNvBZ7oY
bzGVIvNsToCovWfzwjL229uKSQLw1qZBEyA3AlKBkOb+/VxT3tGna/uve3RRWgvu6ny1wz+i/P7dr5M9
bauLgy/pnNlY/eKL+1WUYuVy4eKN6kmIQvILWbOsce/e1eKzfVLr9e4h/C30XY0sS3xtlbv/rJUmMOdG
U3z5jMz151FX6Ot1Yi5h2lh4ucX4YT8GufC2v7fn1EQee+c8bI9aXxZ9eV/T7vwbmsjdrpNVEYrn0Wgo
C6sPzt5hZh0yVHXag8Zvh/UkSTabTbx1T7FAk+A1WxU56oQVPFFy89GbP+se+uoF/W0uk8U7dnP/D0CN
arR70lxq1MZ1kdo/DaI8e1q7Hdt7av0Mlq65khvXuIm5fruUGxHuvIuvBEboyD/ktpJvK4AwArs/8PZ1
2mJd8gy7Lz1MuzUz0LRvk/je3keSwGva0nha+jcMfRGBBlxHLYpi2qCHiLrD1UNBq6jYLrpUAm1kuT4h
JZGG/snutnoUtflolJV2Qft/klEBepvci5b0zM/31aR27ktVpOpFXVet2tR8mxzcHvxfAAAA//+yRx4v
VEAAAA==
`,
	},

	"/assets.go": {
		name:    "assets.go",
		local:   "assets/assets.go",
		size:    0,
		modtime: 1604511948,
		compressed: `
H4sIAAAAAAAC/wEAAP//AAAAAAAAAAA=
`,
	},

	"/details_close.png": {
		name:    "details_close.png",
		local:   "assets/details_close.png",
		size:    686,
		modtime: 1603364414,
		compressed: `
H4sIAAAAAAAC/wCuAlH9iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAACdUlEQVR4Aa2V
30tTYRjHVSgsoQKhXPUPlKZMlImiIIg/pggiiDeCBAdqyC4Kf9zVhVdeelX33QnCbtYvxZsxxkoqKxiz
1SzdFudMb5xO5/bt+fa+sPCw3IVf+PA+532e5ytn53lfK0qoSrggXBauCbUKxtxjjjVnq1IXXxFuCXeE
FqGdMOYec6zRtZX/M6sWrgv1hmHcDwQCLxOJxM9CoZAnjLnHHGt0bbXdVG1cEm4KLp/P9yKXyx2jhJhj
DWvZc9qUwUWhzuFwdMVisc8QFQ4PcbCygvT0NJLDw0gNDSH96DEyfj8KmQwo1rJHem8oD2VapX/sxlAo
9Aqi/N4e9hYWsDMwgARxD2DH7ZZYren5eZxYFqhgMOhnr3BVeSnn216v98Hf3yqXg/X0CX719YFs9/Wq
uJfPGtkzZ2fBWvZ4PB6DHtqrokaol7/0GqLM2hq2enpsxMmpvf3VVVD8UOJxV42Uet1Wy7J+M5mam8P3
7u6ySM7MgDJNM8mRUl5qYDtOREz+GB3FZlcXNjs7UUrMk/jYGKhsNnuo57TWZhgTw0hHO0EpRdpV/tvI
CKgjUdFQv/Lu7q7JZHxqCl9dLqGtSJtL4VJ80Wvc8xD2V9YfRUbmLZPp5WVstLTYaSWt+lmt1tISKH5Q
/VFqbGOTl6GNTk7iQ3Oz4FSrU8UfuTqdBJHxceQz+2APe/8Zm+Jgh8PhNxBlt7YQNQysNzVivbEJ7wXG
iiZEJiZwEI2C4mFgr/aoKnn0jk0TiWfPsTE4iHcN9xBuaMCn/n5sLy7iKJk8ffTqikfvfC4H9laWdX2l
UqltaDEu9/o664LtIOVfsOf4L+APb5yaiwyN8+8AAAAASUVORK5CYIIBAAD//1c8bPquAgAA
`,
	},

	"/details_open.png": {
		name:    "details_open.png",
		local:   "assets/details_open.png",
		size:    709,
		modtime: 1603364414,
		compressed: `
H4sIAAAAAAAC/wDFAjr9iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAACjElEQVR4Aa2V
30uTURjHnVBUgglCaXVTJJVLMdhQm7+1JEvJiKAggmgSQiKJl0V0E13UVf0HQZmBLcvlpqa55tqV0YoM
zIhY6js0yDH11X17vuO8Sq5Zgl/48DznPD/G63nOMSmBkoUNwhYhTUgn9NUeY8z5p0wqOVXYKRwQLMJh
hYV7Kpaqck2rNdskbBPMdrv9osfjcQaDwW/RaHSR0OceY8xhrqox/a3ZZmGHkO9wOB7ouj6PBGKMOcxl
zcqmdDYKGZmZmSWjo6PvIYosRuDWXGj50IwTb4+hxleN5sAVvJh4jvBCGBRzWSO121UPk3EAaUKuz+d7
ycTp+Wnc/nwL1d4qHBVidmjZv/npBkJzGiiv19vFWmGrcVDsvKupqeky/056VMf1j9dQOViBKo9Aa/ix
dbnYcrQGWsBc1jQ2NtrZQ/VKShHM8kvdEPVN9qJsoBRl/aUoHyiJ+UpcCxJTtmfCDYoHJT2yYyOlPtca
CoUmGGwdbkVRbxGK+2y0gg2GisUvNmJCy/BVUJqm/eBIxXqpgbUtiBise12HQlc+ClwFSKRCiZH6wXpQ
s7OzETWn6XENa/trYemywuK0IpGsTotgRU3fcVBzouWG6pOnpqY0BhuGGpDXeUjIW7JKcfuX3tjjP9k4
FBkZN4PtY+042JGzzNMcGDJ35C7tmcU++tJmjE63OpSUuLEJ62GcfXUO+59kr8rJnlOY0WfAGtYaY/PH
YPv9fhdEY7++4nz/BWS17UPWY0Es2avWp3vOYOTnCCheBtaqHskJr95kZBL3AvdR2XkEex5mYbdQ+qwC
d97dRTAcXHn1Moyrt16PA2tN//V8jY+Pf4cS/VWerzU9sDay1gd2Xf4F/AZqlpeB9836LwAAAABJRU5E
rkJgggEAAP//wNSxe8UCAAA=
`,
	},

	"/index.html": {
		name:    "index.html",
		local:   "assets/index.html",
		size:    6155,
		modtime: 1604511885,
		compressed: `
H4sIAAAAAAAC/6xYbXPbtrL+7l+x5Z07TuaKpPySNE0ltc2Lm/Q2L62d3uRTZwUsRVggwAKgZPZOz385
H8/v6B87syAly7ScpJ3TmcYiuNx9dp/dxQKTL569eXrx4e1zKEOlZwcT/gMazWKakEl4gVDODgAmX6Qp
/GhXyix0CyUaKRwWgSTMW3iFLigDL6z2Ac7XZCTBt1Xpu1/KwPH46MsRNLVE/iIuHI8hTaPmigJCGUKd
0m+NWk2Tp9YEMiG9aGtKQHRP0yTQVcgZ4NcgSnSewvTdxVn6KLnWYrCiabJStK6tCzvfrpUM5VTSSglK
48MIlFFBoU69QE3ToxH40imzTINNCxWmxiZbx8+FU3XwgI7g8reGXDuCubXBB4c1oJEgMWDAuSa/ccvH
b8A7MU3YO/84z4WVlHUKMmGrvPuZnmQPsnFWKZNd+gSUCbRwKrTTxJd4/OBhevX699fHeKrD8snp6SuR
//D7SX1xqt4diYp+Hp8t3/vT2jX5D1f40zQBEM56b51aKDNN0FjTVrbxyWySd5juhOcDimWNocy2zglp
ItLtQn6anWZH+aW/XroD+cmj03RdnD87O37+YPzh+NlR805ejt+cNK+e/GAum3fPTl+WX35Y4wd5pH4r
luFy/M7KR98/fX6lT94sHqli/eRh8tedyXPGfM1HZijkR9nRODseM+w+/Cxw0Qn08G+qZNqfnp+DI28b
J6gj/5p0SQU2Ooyg1o3fpb9/sUkDrcwSHOlp4kOryZdEIYHSUfG34i78MPDC7438L0trH12dPv3evzn5
nxfl1erRRf7Tg7f4Piz/NzQPm8WDizf0+peHiyfqjP7v7fdnr7961ZRviuOTn756WVyWd0f+U159lADG
v58B9mN2MMm7jnMwiYrZWOao1iioov8/gPhfhVddET+Go/F4XF99fQDwxwFAkJmkgEr7lEvfWQ2bb+Yo
lgtnGyMfQ+P0vcO8l/zV1mSy2iwO74OxqaOaMIAgE8j1f77udYjGeeseQ23VZjladZkv7dr8PfNCW0+f
tv/HwSTvQ3IwmVvZRh6kWoHQ6P00YYuoDLm00I2SkSeASXk0e6FWNMnLo9mkdHm/vPOhs+teeKhQp0fb
NzffGVxBoekqFVY3lQGDq7RWWnMqymnSP6QB5wk4q2macC4oHxJApzC1TpEJGJQ102RFLiiBescWwAR3
bKUx31AEtaKbFkpbUWeG0ykNdrFga/xyk4//tSu7A6eH0jPlb+rsX3rSJALJaRJcQ8nsgnwA36hAfpLj
x/HeBOrINzr4z8Xai38O3K3oAHGB2veQ/yrYirzHBX022o3858C9lt2P97u5bcINvJNcqtU2Q288DNN1
fEe+Bpyn/TBwK0P7ceNm9g2+rdEQFCgJuNLvzMQd//kL3fuocU5ak5y3exJ31yzX6/Hs+RWJhgelwNT1
yVYeDwTr2UVJnnaE4g6FK1Sau+ooziUCDcwJtEVJMoOnWoklWAOHP1qUhxBsfAUIghy3jy65s0le3zL3
soDWNp28pxU51H0pjOILNiVsVTMKZaRaKdmgjvgEevJsVqqiIEcmgGuMz7vPc6G5G/jbRuMGssODJoj/
pnPrJDmSHQWF0hTXeQ+PP25wuZsxHyV3b8X+BU53a/wuWpU10Ms9homv0USjWxZ/5Rk2mb22oVRm0RMH
LYVJzsKzvZmwT48kLz6qZ3+wWQldkdh6vyf6PjhVc34OuOim7ORoPP7v/ygTe9rLp6i40cFucxGbDPQb
4+14PqHCOorvR7AmkEpCiSviA4Un4xufxkDzIQIqVEa3ENYWCusqPgCADxgoitxQDbEm59qKpSi52qII
3GsJSwglcf3y/1DQGirr6H4GF2Vf47Dm9wsy5PgYNVC8UgioKZQ5CxMfcNhW3QSuOwRHtfUqWNdmcOZs
BaHEEFdHoAKs0QNd1bEVDzRHwa5EIRBWHlTFxysG3CNjS9R1LVgrzjh+qRzwVCQaH2w1VEo+pCU6Q96T
39tvXtv1qDMulTSHAdbWLYF5q8kVJIJuY0O7xtXLoV5j66FutIYOycC4RjYPPYUMfl0Sh59lW+7uDWrd
blySu576OGsbLqY1Dtk1lqcDRxk8U7JTJqxzESusyKmiBe6cbSzKb+BlH3hfk1BschglZxsekG1FDNFA
iU4W1i37ZMC6dhYFK+v8SKyt/QhKamPeCltVPEEOKeUgxhC8fw9zEth42iRBgUors0j2UnLBGN7++S8e
Tc9/V/rPfy5aBfe+XaJDrsL7UCL7rTwoSTji/cU1ps8eD8GGGNi5RrEcYJrbqww+2AZ8rQw0NSAYG68P
vJJcE9KKJY/Emzl3xFXmQgSuQrmH585sGqNbKMGfFqqPVEEk+VOmNhakz+A7Y2MWDC0N1B5aJ0riE1gg
f7hNjk6vtGvDzdbHdTJBue51rDUouPQWKpTNfKD13q220NuPin7+8W3awbyfwbkdARZMAvold3eW2FSo
HejdKdZOwQhQ6/i844h1h2CIGLYFaUF5iKc0SNYlhkPPO7zbX0ZR6zdJ536f5CoALpTxnd1NYwGNPkTx
Lg63GdsMC3dkn/XbOnRcEcjNjcBYV8W8CqiXHjA291gvvMABiksDW0mpVtT18SSDF3bNlTmKTZ/dpxWZ
2IPZJ49B8UjllREE2OXJUN9uNJM4DkkLtu8ryiziztA1BTTgyUhA04KhEDtbv2VFiYHqNUZmYzC5KNLG
SHIRO2cDFOhivaP2ttuouijF7tlTwr8Hagv0IfWtEZsxkRurdRXJjsxeiQVRklh22hhCfVxzWmmqNoe4
gWJpycdmWOEydpbaeq/iABGz65k97zasqtZcmVEHYAgY6/CcPWWu0Q0TpPNwS1wG+xJlyyUPRTH9OX5S
+aCMYFOPNyzHDZy3ICN4YIZgrb5dQpNGzwZL8Q5kttnzQnfG0mq/mDKMBJtgq3gBusZ2dLd0cIThZlXH
fSc2TW6TFB8L5PLfRjbbp3CSD5HfDtd2GmJzz8+6yHSOWbd3OjqzcaOM1Qz/OIGW0PmYfzH1ynieiBx5
cityvAUYdkgZqJ2VTeQgG2DdXIbxhx23FEpJK1v7TNk8482SDw1wfJp/2eVnv9EXFLjwekz87Z6u4ruW
E7d5aqq8W+OenH0qQJtLk+uVk9kzmjc8VS8meXkyjJDrxmjJMjwI1+5jY/Bdx9vtz/7HJO+ufQ7i3WQ8
hrHHWNfxrnFzCRramvrL8ktcYbea9HejWNeDq85J3l39/zsAAP//qRsA9AsYAAA=
`,
	},

	"/viewer.html": {
		name:    "viewer.html",
		local:   "assets/viewer.html",
		size:    2723,
		modtime: 1603658490,
		compressed: `
H4sIAAAAAAAC/6xW23LbyBF991e0R5Uqu0IA4k2RIICp2LGcOJZkO4pjPw6ABjHiYGZ2psGLt/bftwYA
Seiy+7C10gPJnr6cPt04g+TlP2/f3n3/9A4qquXiReI/QHK1TBkq5g3Ii8ULgKRG4pBX3DqklDVUBues
PSBBEhelkAhrgRu0SdSZDlGK15iyAl1uhSGhFYNcK0JFKfsHuJpL2YdCqS0QbmnvMAKhnBEWC8h2sBRU
NRk43dh8X409rsMbqrQdlKi0FDVXnaMUagUWZcoc7SS6CpEYVBbLlFVExsVR5IjnK8OpCjOtyZHlJi9U
mOs6OhiiWTgLx1Hu3NEW1kKFuXMMhCJcWkG7lLmKT89nwdeV1ufb2dv37nb6139V2/X5XfR5/ol/o9V/
qDlrlvO7W7z5erZ8I67w/5/eX91cXDfVbTmZfr74d3lfMcitdk5bsRQqZVxptat147qu2l78N4BQNXUc
Z1hqi/Bza/J/PRsxcCL7SgqFry/bw18OUUfnTNsCbWDFsqJ4bLbgtBQFnBTjYl7wy4PfRhRUxTDF+nJQ
SGobg11m/NXkb6PpeDSdj8Lpw2q5Lobg9BptKfUmhrVwIpN4TFdqRUHJayF3Mfz36lorHXzBZSO5Hb3V
ymnJ3eijyNByv1ngHUbXqKQe1VppZ3j+OJsTPzCG8cRsn6A+mcwmF5NBwEbbIthYbmJQ2tZcDo4qQRi0
BWIwFocNkg0rsaykJxCLQacZz1dLqxtVBPuSZVlmRTGMPqm5UMcYw4tCqOUQcu8nNS+yhkirQYl+KGf7
ofSIeCbxMe/Po7l8tAcx/M4K7FeFF6JxMUyHpPZIxqenfxlCKcQ69LKC9oik5nYpVAznZgun/v/ymfbP
hsl7c0DatGFPTzJNpOtHh8+1fFael/yPdE3aBBJLer79gVP7JD316p8GL3iB39bBaP6MvYeXojbaEld0
rJdEvVi0utEqMjibH9XP70h4/1ODdtdKXvc1mIbz8LRVuPsnAjeZnwXbmx83Ez6TtHozm13n0YcfU3M3
E/8b5zV+Ob1afXMzY5vow5Z/Tn9bzJKog7QYoKOdwZR5kqJ7vuadlXWgI25M0F0EHtez8aJIGW55bST6
JGyYsNSadbp5VwkHwoHTNYJrvdubKITvuoGcK/BPGyjcgL/rHKwFB6oQpCCSCEKZhoBneo0j4KoALp1u
M+8dGytDeBcuQ2B/9ynSrkpIW2JdCK5RQXtDkQbDLYncD9yb0IUv2mxSrPBpgpOP81PWTbfvP4m6qzvJ
dLFr6SjEuuXCq0vftLct+p1LSm1r0Mo1WS0oZUeu4xIpr66ExFevLy1SYxWUXDpki8O+ttlzyZ1LWUtF
4J8yM/AASDqOjvSzfYQvHfgrymrJwEieY6VlgTZlke+05agF73/5QbDoQebnqwfcGFTFAxAASS+ZHY6u
3S75UU8PyDJSkJEKjBU1t7tHqQCuPDWPbEM0PiVaBlZLX4w4NY4Bt4IHlSgKVCkj26Df3MEs+jxRB+ZB
pw/dHvxMIs9jP9njwRBOp7v9O9dBdw5dJc5w1S0JEmeLebd6ML64gDdJ5E8Prrz1s3wTNFayxRe+SSL+
tHh78ezLe23pqN6/vCVR69AuaBfVL2wSda+kvwYAAP//0Gc+kaMKAAA=
`,
	},

	"/": {
		name:  "/",
		local: `assets/`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"assets/": {
		_escData["/app-viewer.js"],
		_escData["/app.js"],
		_escData["/assets.go"],
		_escData["/details_close.png"],
		_escData["/details_open.png"],
		_escData["/index.html"],
		_escData["/viewer.html"],
	},
}
