FROM gcr.io/evmchain/internal-devnet-protocol:latest

#ENV PROTOCOL_LAYER=L1/L2
ENV LOG_LEVEL=debug
#ENV MAINNET_URL=programmatically generated
#ENV NETWORK_HOST=programmatically generated
#ENV PRIVATE_KEY=(L2 deployer private key)(secret)
#ENV L2_GENESIS_HASH=(L2 genesis hash)
#ENV TAIKO_L2_ADDRESS(L2 taiko address)
#ENV L2_SIGNAL_SERVICE=(L2 signal service l2 address)
#ENV GUARDIAN_PROVERS=(L2 guardian prover addresses)(join ",")
#ENV CONTRACT_OWNERS=(L2 contract owner)
#ENV TAIKO_TOKEN_PREMINT_RECIPIENT=(L2 token recipient address)
#ENV SHARED_ADDRESS_MANAGER=(L2 value: "0x0000000000000000000000000000000000000000")
#ENV TIMELOCK_CONTROLLER=(L2 value: "0x0000000000000000000000000000000000000000")